<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/db.php';
$pdo->exec("SET FOREIGN_KEY_CHECKS=0");
$ts = '2026-04-15 08:00:00';
$lid = (int)$pdo->query("SELECT COALESCE(MAX(id),0)+1 FROM lms_lessons")->fetchColumn();
$s = $pdo->prepare("INSERT IGNORE INTO lms_lessons (id,course_id,title,content,sort_order,is_published,created_at) VALUES (?,?,?,?,?,1,?)");
function L(PDOStatement $s,int &$lid,int $cid,string $t,string $c,int $sort,string $ts):void{$s->execute([$lid++,$cid,$t,$c,$sort,$ts]);}

L($s,$lid,19,"Introduction to Machine Learning",
"## What is Machine Learning?\n\nMachine Learning is a subset of AI that enables systems to learn and improve from experience without being explicitly programmed. Instead of writing rules, you provide data and the algorithm discovers the rules.\n\n## Why Machine Learning Now?\n\n- Data explosion: Smartphones, IoT, social media generate massive data\n- Computing power: GPUs make training large models feasible\n- Algorithm advances: Better architectures and optimisation methods\n- Open source: TensorFlow, PyTorch, scikit-learn freely available\n\n## The ML Landscape\n\nArtificial Intelligence > Machine Learning > Supervised Learning (Classification, Regression), Unsupervised Learning (Clustering, Dimensionality Reduction), Reinforcement Learning > Deep Learning (CNNs, RNNs, Transformers)\n\n## Your First ML Model\n\n```python\nfrom sklearn.datasets import load_breast_cancer\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import accuracy_score\n\ndata = load_breast_cancer()\nX, y = data.data, data.target\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nmodel = LogisticRegression(max_iter=10000)\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\nprint(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')\n```\n\n## Practical Task\n\nBuild your first ML model to predict whether a student will pass or fail based on: study hours, attendance percentage, assignment completion rate, and previous test scores. Use Logistic Regression. Report accuracy, precision, and recall.\n\n## Self-Check\n1. What is the difference between AI and Machine Learning?\n2. Name the 3 main types of machine learning.\n3. What is the purpose of splitting data into training and test sets?",
1,$ts);

L($s,$lid,19,"Supervised Learning: Regression",
"## Regression Algorithms\n\nRegression predicts a continuous numerical value. It answers: How much? How many? What price?\n\n## Linear Regression\n\n```python\nfrom sklearn.linear_model import LinearRegression, Ridge, Lasso\nfrom sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\nimport numpy as np\n\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\n\nprint(f'MAE:  {mean_absolute_error(y_test, y_pred):.2f}')\nprint(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}')\nprint(f'R2:   {r2_score(y_test, y_pred):.4f}')\n\nridge = Ridge(alpha=1.0)   # L2 regularisation\nlasso = Lasso(alpha=0.1)   # L1 regularisation (feature selection)\n```\n\n## XGBoost Regression\n\n```python\nimport xgboost as xgb\nfrom sklearn.model_selection import GridSearchCV\n\nxgb_model = xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, max_depth=6, random_state=42)\n\nparam_grid = {'n_estimators':[100,200],'learning_rate':[0.05,0.1],'max_depth':[4,6,8]}\ngrid = GridSearchCV(xgb_model, param_grid, cv=5, scoring='r2')\ngrid.fit(X_train, y_train)\nprint(f'Best R2: {grid.best_score_:.4f}')\n```\n\n## Regression Metrics\n\n- MAE: Mean Absolute Error — average absolute difference\n- RMSE: Root Mean Squared Error — penalises large errors more\n- R2: Proportion of variance explained (1.0 = perfect)\n- MAPE: Mean Absolute Percentage Error — interpretable as %\n\n## Practical Task\n\nBuild a house price prediction model for Lagos properties. Features: size (sqm), bedrooms, bathrooms, location, age, parking spaces. Compare Linear Regression, Ridge, and XGBoost. Use RMSE and R2 as metrics.\n\n## Self-Check\n1. What is the difference between MAE and RMSE?\n2. What is regularisation and why is it needed?\n3. When would you use Lasso over Ridge regression?",
2,$ts);

L($s,$lid,19,"Supervised Learning: Classification",
"## Classification Algorithms\n\nClassification predicts which category an input belongs to.\n\n## Logistic Regression\n\n```python\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import classification_report, roc_auc_score\n\nmodel = LogisticRegression(C=1.0, max_iter=1000)\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\ny_prob = model.predict_proba(X_test)[:,1]\n\nprint(classification_report(y_test, y_pred))\nprint(f'ROC-AUC: {roc_auc_score(y_test, y_prob):.4f}')\n```\n\n## Random Forest\n\n```python\nfrom sklearn.ensemble import RandomForestClassifier\n\nrf = RandomForestClassifier(n_estimators=200, max_depth=10, n_jobs=-1, random_state=42)\nrf.fit(X_train, y_train)\n\nimportances = pd.Series(rf.feature_importances_, index=feature_names)\nimportances.nlargest(10).plot(kind='barh')\n```\n\n## XGBoost Classification\n\n```python\nimport xgboost as xgb\n\nmodel = xgb.XGBClassifier(n_estimators=300, learning_rate=0.05, max_depth=6,\n                           subsample=0.8, colsample_bytree=0.8, random_state=42)\nmodel.fit(X_train, y_train, eval_set=[(X_test, y_test)],\n          early_stopping_rounds=20, verbose=False)\n```\n\n## Handling Imbalanced Classes\n\n```python\nfrom imblearn.over_sampling import SMOTE\nsmote = SMOTE(random_state=42)\nX_resampled, y_resampled = smote.fit_resample(X_train, y_train)\n\n# Or use class_weight\nmodel = RandomForestClassifier(class_weight='balanced')\n```\n\n## Practical Task\n\nBuild a fraud detection model for mobile money transactions. Handle class imbalance. Compare models. Optimise for recall (catching fraud is more important than false alarms).\n\n## Self-Check\n1. What is the difference between precision and recall? Which matters more for fraud detection?\n2. What is a Random Forest and how does it differ from a single Decision Tree?\n3. What is SMOTE and when do you use it?",
3,$ts);

L($s,$lid,19,"Unsupervised Learning",
"## What is Unsupervised Learning?\n\nUnsupervised learning finds hidden patterns in data without labelled examples.\n\n## K-Means Clustering\n\n```python\nfrom sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\n# Elbow method to find optimal k\ninertias = []\nfor k in range(1, 11):\n    km = KMeans(n_clusters=k, random_state=42, n_init=10)\n    km.fit(X_scaled)\n    inertias.append(km.inertia_)\n\n# Fit with optimal k\nkm = KMeans(n_clusters=4, random_state=42, n_init=10)\ndf['cluster'] = km.fit_predict(X_scaled)\n```\n\n## DBSCAN\n\n```python\nfrom sklearn.cluster import DBSCAN\ndbscan = DBSCAN(eps=0.5, min_samples=5)\ndf['cluster'] = dbscan.fit_predict(X_scaled)\n# Cluster -1 = outliers/noise\n```\n\n## PCA — Dimensionality Reduction\n\n```python\nfrom sklearn.decomposition import PCA\n\npca = PCA(n_components=2)\nX_2d = pca.fit_transform(X_scaled)\nprint(f'Variance retained: {pca.explained_variance_ratio_.sum():.3f}')\n\nimport matplotlib.pyplot as plt\nplt.scatter(X_2d[:,0], X_2d[:,1], c=y, cmap='viridis')\n```\n\n## Anomaly Detection\n\n```python\nfrom sklearn.ensemble import IsolationForest\niso = IsolationForest(contamination=0.05, random_state=42)\ndf['anomaly'] = iso.fit_predict(X_scaled)  # -1=anomaly, 1=normal\n```\n\n## Practical Task\n\nPerform customer segmentation for a Nigerian e-commerce company. Features: purchase frequency, average order value, days since last purchase. Use K-Means (find optimal k). Visualise with PCA. Name each segment and write a marketing strategy for each.\n\n## Self-Check\n1. What is the difference between K-Means and DBSCAN?\n2. What does PCA do and why is it useful?\n3. What is anomaly detection and give a real-world use case?",
4,$ts);

L($s,$lid,19,"Model Evaluation & Hyperparameter Tuning",
"## Train/Validation/Test Split\n\n```python\nfrom sklearn.model_selection import train_test_split\n\nX_trainval, X_test, y_trainval, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\nX_train, X_val, y_train, y_val = train_test_split(X_trainval, y_trainval, test_size=0.25, random_state=42)\n# Result: 60% train, 20% val, 20% test\n```\n\n## Cross-Validation\n\n```python\nfrom sklearn.model_selection import cross_val_score, StratifiedKFold\n\ncv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\nscores = cross_val_score(model, X, y, cv=cv, scoring='f1_macro')\nprint(f'CV F1: {scores.mean():.4f} +/- {scores.std():.4f}')\n```\n\n## Optuna — Bayesian Optimisation\n\n```python\nimport optuna\n\ndef objective(trial):\n    params = {\n        'n_estimators': trial.suggest_int('n_estimators', 50, 500),\n        'max_depth': trial.suggest_int('max_depth', 3, 12),\n        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n    }\n    model = xgb.XGBClassifier(**params, random_state=42)\n    return cross_val_score(model, X_train, y_train, cv=5, scoring='roc_auc').mean()\n\nstudy = optuna.create_study(direction='maximize')\nstudy.optimize(objective, n_trials=100)\nprint(f'Best params: {study.best_params}')\n```\n\n## Learning Curves\n\n```python\nfrom sklearn.model_selection import learning_curve\n\ntrain_sizes, train_scores, val_scores = learning_curve(model, X, y, cv=5, n_jobs=-1)\nplt.plot(train_sizes, train_scores.mean(axis=1), label='Training')\nplt.plot(train_sizes, val_scores.mean(axis=1), label='Validation')\nplt.legend()\n```\n\n## Practical Task\n\nTune your fraud detection model using Optuna (100 trials). Plot learning curves to diagnose overfitting/underfitting. Compare tuned vs untuned model. Report the improvement in ROC-AUC.\n\n## Self-Check\n1. What is the difference between Grid Search and Bayesian Optimisation?\n2. What do learning curves tell you about your model?\n3. Why should you never tune hyperparameters on the test set?",
5,$ts);

L($s,$lid,19,"Feature Engineering & Selection",
"## Feature Engineering\n\nFeature engineering creates new variables that better represent underlying patterns.\n\n```python\n# Interaction features\ndf['income_to_loan_ratio'] = df['income'] / (df['loan_amount'] + 1)\ndf['age_times_experience'] = df['age'] * df['work_experience']\n\n# Date features\ndf['hour'] = df['timestamp'].dt.hour\ndf['is_business_hours'] = df['hour'].between(9, 17).astype(int)\ndf['days_since_registration'] = (pd.Timestamp.now() - df['reg_date']).dt.days\n\n# Aggregation\ndf['avg_score_by_course'] = df.groupby('course')['score'].transform('mean')\ndf['rank_in_course'] = df.groupby('course')['score'].rank(ascending=False)\n```\n\n## Feature Selection\n\n```python\nfrom sklearn.feature_selection import SelectKBest, f_classif, RFE\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Filter: Statistical test\nselector = SelectKBest(f_classif, k=10)\nX_selected = selector.fit_transform(X, y)\n\n# Wrapper: Recursive Feature Elimination\nrfe = RFE(RandomForestClassifier(n_estimators=50), n_features_to_select=10)\nrfe.fit(X_train, y_train)\n\n# Embedded: Tree feature importance\nrf = RandomForestClassifier(n_estimators=100)\nrf.fit(X_train, y_train)\ntop_features = pd.Series(rf.feature_importances_, index=X.columns).nlargest(10).index\n\n# SHAP values\nimport shap\nexplainer = shap.TreeExplainer(rf)\nshap_values = explainer.shap_values(X_test)\nshap.summary_plot(shap_values[1], X_test)\n```\n\n## Practical Task\n\nTake a dataset with 50+ features. Apply feature engineering to create 10 new features. Use 3 different feature selection methods. Compare model performance with all features vs top 10. Which approach gives the best result?\n\n## Self-Check\n1. What is the difference between filter, wrapper, and embedded feature selection?\n2. What are SHAP values and why are they useful?\n3. Why can too many features hurt model performance?",
6,$ts);

L($s,$lid,19,"ML Deployment & MLOps",
"## Saving and Loading Models\n\n```python\nimport joblib\n\n# Save\njoblib.dump(model, 'model.joblib')\njoblib.dump(scaler, 'scaler.joblib')\n\n# Load\nmodel = joblib.load('model.joblib')\nscaler = joblib.load('scaler.joblib')\n```\n\n## Flask REST API\n\n```python\nfrom flask import Flask, request, jsonify\nimport joblib, numpy as np\n\napp = Flask(__name__)\nmodel = joblib.load('model.joblib')\nscaler = joblib.load('scaler.joblib')\n\n@app.route('/predict', methods=['POST'])\ndef predict():\n    data = request.get_json()\n    features = np.array(data['features']).reshape(1, -1)\n    features_scaled = scaler.transform(features)\n    prediction = model.predict(features_scaled)[0]\n    probability = model.predict_proba(features_scaled)[0].max()\n    return jsonify({'prediction': int(prediction), 'probability': float(probability)})\n\nif __name__ == '__main__':\n    app.run(host='0.0.0.0', port=5000)\n```\n\n## MLflow Experiment Tracking\n\n```python\nimport mlflow, mlflow.sklearn\n\nwith mlflow.start_run():\n    model = RandomForestClassifier(n_estimators=100, max_depth=6)\n    model.fit(X_train, y_train)\n    accuracy = accuracy_score(y_test, model.predict(X_test))\n    mlflow.log_param('n_estimators', 100)\n    mlflow.log_metric('accuracy', accuracy)\n    mlflow.sklearn.log_model(model, 'model')\n```\n\n## Model Monitoring\n\nModels degrade over time as data distribution changes (data drift). Monitor:\n- Prediction distribution over time\n- Feature distribution vs training data\n- Model performance on labelled production samples\n\nTools: Evidently AI, WhyLabs, Arize, MLflow\n\n## Practical Task\n\nDeploy your best model as a Flask REST API. Containerise with Docker. Set up basic monitoring: log every prediction with timestamp, input features, and output. Create a dashboard showing prediction volume and average confidence over time.\n\n## Self-Check\n1. What is data drift and why does it matter for deployed models?\n2. What is MLflow used for?\n3. What is the difference between model deployment and MLOps?",
7,$ts);

L($s,$lid,19,"Capstone: ML System in Production",
"## Final Project: Customer Churn Prediction\n\nYou are the lead ML engineer at a Nigerian telecommunications company. Build a model to predict which customers are likely to churn in the next 30 days.\n\n## Dataset Features\n\ncustomer_id, tenure_months, monthly_charge, total_charges, contract_type (month-to-month/1-year/2-year), internet_service, phone_service, payment_method, num_support_calls, num_complaints, churn (target: 0=stayed, 1=churned)\n\n## Phase 1: Exploratory Analysis\n- Churn rate overall and by segment\n- Feature distributions for churned vs retained customers\n- Correlation analysis\n- Identify top 5 churn risk factors\n\n## Phase 2: Feature Engineering\n- Create charge_per_month_tenure ratio\n- Encode contract type (ordinal)\n- Create high_support_user flag (calls > 3)\n- Scale numeric features\n\n## Phase 3: Modelling\n- Baseline: Logistic Regression\n- Advanced: XGBoost with Optuna tuning\n- Handle class imbalance with SMOTE\n- Evaluate: ROC-AUC, Precision-Recall curve, F1\n- Interpret: SHAP values for top 10 features\n\n## Phase 4: Business Impact\n- Calculate expected revenue saved if top 20% at-risk customers are retained\n- Determine optimal probability threshold\n- Create customer risk segments: High/Medium/Low\n\n## Phase 5: Deployment\n- Flask API: POST /predict with customer features, returns churn probability and risk segment\n- Streamlit dashboard: Upload CSV, get predictions, download results\n- MLflow: Track all experiments\n- Docker: Containerise the application\n\n## Deliverables\n1. GitHub repository (clean code, README, requirements.txt)\n2. Jupyter Notebook with complete analysis\n3. Deployed Flask API\n4. Streamlit dashboard\n5. Business presentation (10 slides)\n6. Model card (purpose, performance, limitations, fairness)\n\n## Evaluation Criteria\n- EDA quality and business insight (15%)\n- Feature engineering (15%)\n- Model performance ROC-AUC > 0.80 (25%)\n- Code quality and MLOps practices (20%)\n- Business impact analysis (15%)\n- Presentation and documentation (10%)\n\n## Self-Check\n1. What ROC-AUC score did you achieve and is it good enough for production?\n2. How would you explain the model decision to a customer flagged as high churn risk?\n3. What would you monitor in production to detect model degradation?",
8,$ts);

$pdo->exec("SET FOREIGN_KEY_CHECKS=1");
echo "ML: 8 lessons done\n";
echo "Total lessons courses 17-19: ".$pdo->query("SELECT COUNT(*) FROM lms_lessons WHERE course_id IN (17,18,19)")->fetchColumn()."\n";
