<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/db.php';

$pdo->exec("SET FOREIGN_KEY_CHECKS=0");
$ts = '2026-04-15 08:00:00';

echo "=== Adding 3 new courses ===\n";

/* ── 1. INSERT COURSES ── */
$courses = [
    [17, 'Data Science',                  'data-science',           'Master data science from data wrangling to machine learning, statistical analysis, and real-world project deployment.',                    'From raw data to actionable insights.',  380000.00, 'advanced'],
    [18, 'Artificial Intelligence (AI)',  'artificial-intelligence','Comprehensive AI course covering neural networks, deep learning, NLP, computer vision, and AI ethics with hands-on projects.',           'Build intelligent systems with AI.',     420000.00, 'advanced'],
    [19, 'Machine Learning (ML)',         'machine-learning',       'Learn supervised, unsupervised, and reinforcement learning algorithms, model evaluation, feature engineering, and ML deployment.',        'Algorithms that learn from data.',       400000.00, 'advanced'],
];

$cStmt = $pdo->prepare("INSERT IGNORE INTO lms_courses (id,title,slug,description,short_description,price,level,is_active,created_at) VALUES (?,?,?,?,?,?,?,1,?)");
foreach ($courses as $c) {
    $cStmt->execute($c + [8 => $ts]);
    echo "Course: {$c[1]}\n";
}

/* ── 2. INSERT EXAMS ── */
$exams = [
    [61, 17, 'Data Science — Final Exam',               40, 10, 50],
    [62, 18, 'Artificial Intelligence — Final Exam',    40, 10, 50],
    [63, 19, 'Machine Learning — Final Exam',           40, 10, 50],
];
$eStmt = $pdo->prepare("INSERT IGNORE INTO lms_exams (id,course_id,title,duration_minutes,total_questions,pass_mark,total_marks,is_published,created_at) VALUES (?,?,?,?,?,?,?,1,?)");
foreach ($exams as $e) {
    $eStmt->execute([$e[0],$e[1],$e[2],$e[3],$e[4],$e[5],$e[4],$ts]);
    echo "Exam: {$e[2]}\n";
}

/* ── 3. INSERT LESSONS ── */
$lid = 115;
function ins_lesson(PDO $pdo, int &$lid, int $cid, string $title, string $content, int $sort, string $ts): void {
    $pdo->prepare("INSERT IGNORE INTO lms_lessons (id,course_id,title,content,sort_order,is_published,created_at) VALUES (?,?,?,?,?,1,?)")
        ->execute([$lid++, $cid, $title, $content, $sort, $ts]);
}

/* ── DATA SCIENCE (course_id=17) ── */
ins_lesson($pdo,$lid,17,"Introduction to Data Science",
"## What is Data Science?\n\nData science is an interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data.\n\n## The Data Science Lifecycle\n\n1. **Problem Definition**: What business question are we answering?\n2. **Data Collection**: Gather data from databases, APIs, web scraping, surveys\n3. **Data Cleaning**: Handle missing values, outliers, duplicates, inconsistencies\n4. **Exploratory Data Analysis (EDA)**: Understand distributions, correlations, patterns\n5. **Feature Engineering**: Create and select the most predictive variables\n6. **Modelling**: Apply statistical or machine learning models\n7. **Evaluation**: Measure model performance with appropriate metrics\n8. **Deployment**: Serve the model in production\n9. **Monitoring**: Track model performance over time\n\n## Data Science vs Related Fields\n\n- **Data Analysis**: Focuses on describing and interpreting existing data\n- **Data Engineering**: Builds pipelines and infrastructure for data\n- **Machine Learning**: Algorithms that learn patterns from data\n- **Data Science**: Combines all three with domain expertise\n\n## Essential Tools\n\n- **Python**: Primary language (pandas, numpy, scikit-learn, matplotlib)\n- **R**: Statistical computing and visualisation\n- **SQL**: Query and manipulate relational databases\n- **Jupyter Notebook**: Interactive development environment\n- **Git**: Version control for code and experiments\n\n## Practical Task\n\nInstall Anaconda (anaconda.com). Create a new Jupyter Notebook. Import pandas and numpy. Load a CSV file (download any dataset from Kaggle). Display the first 10 rows, check data types, and count missing values.\n\n## Self-Check\n1. What are the 9 stages of the data science lifecycle?\n2. What is the difference between data science and data analysis?\n3. What Python libraries are essential for data science?",
1,$ts);

ins_lesson($pdo,$lid,17,"Python for Data Science",
"## Why Python for Data Science?\n\nPython dominates data science because of its readable syntax, massive ecosystem of libraries, and strong community support.\n\n## NumPy — Numerical Computing\n\n```python\nimport numpy as np\n\n# Arrays\narr = np.array([1, 2, 3, 4, 5])\nmatrix = np.array([[1,2,3],[4,5,6],[7,8,9]])\n\n# Operations\nprint(arr.mean())      # 3.0\nprint(arr.std())       # 1.41\nprint(arr ** 2)        # [1, 4, 9, 16, 25]\nprint(matrix.shape)    # (3, 3)\nprint(matrix.T)        # Transpose\n\n# Random\nnp.random.seed(42)\nsamples = np.random.normal(loc=0, scale=1, size=1000)\n```\n\n## pandas — Data Manipulation\n\n```python\nimport pandas as pd\n\n# Load data\ndf = pd.read_csv('students.csv')\n\n# Explore\nprint(df.shape)           # (rows, cols)\nprint(df.dtypes)          # Column types\nprint(df.describe())      # Statistical summary\nprint(df.isnull().sum())  # Missing values\n\n# Select\ndf['score']                          # Single column\ndf[['name', 'score', 'grade']]       # Multiple columns\ndf[df['score'] > 70]                 # Filter rows\ndf.loc[0:5, 'name':'score']          # Slice\n\n# Clean\ndf.dropna(subset=['score'])          # Drop rows with null score\ndf['score'].fillna(df['score'].mean()) # Fill nulls with mean\ndf.drop_duplicates(subset=['email']) # Remove duplicates\n\n# Aggregate\ndf.groupby('course')['score'].agg(['mean','min','max','count'])\n```\n\n## matplotlib & seaborn — Visualisation\n\n```python\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\n# Distribution\nsns.histplot(df['score'], bins=20, kde=True)\nplt.title('Score Distribution')\nplt.show()\n\n# Correlation heatmap\nsns.heatmap(df.corr(), annot=True, cmap='coolwarm')\n\n# Scatter plot\nsns.scatterplot(data=df, x='study_hours', y='score', hue='grade')\n```\n\n## Practical Task\n\nDownload the Nigerian Students Performance dataset from Kaggle (or create one with 100 rows). Load it into pandas. Perform: (1) data cleaning, (2) descriptive statistics, (3) a correlation analysis, (4) 3 visualisations. Write a 1-paragraph insight summary.\n\n## Self-Check\n1. What is the difference between a NumPy array and a pandas DataFrame?\n2. How do you handle missing values in pandas?\n3. What chart type would you use to show the correlation between two variables?",
2,$ts);

ins_lesson($pdo,$lid,17,"Statistical Analysis & Probability",
"## Why Statistics in Data Science?\n\nStatistics provides the mathematical foundation for understanding data, making inferences, and validating models. Without statistics, you cannot distinguish signal from noise.\n\n## Descriptive Statistics\n\n**Measures of Central Tendency:**\n- Mean: Sum / Count. Sensitive to outliers.\n- Median: Middle value. Robust to outliers.\n- Mode: Most frequent value.\n\n**Measures of Spread:**\n- Variance: Average squared deviation from mean\n- Standard Deviation: Square root of variance\n- IQR: Q3 - Q1 (robust to outliers)\n- Range: Max - Min\n\n**Shape:**\n- Skewness: Asymmetry of distribution (positive = right tail)\n- Kurtosis: Heaviness of tails\n\n## Probability Fundamentals\n\n- **P(A)**: Probability of event A (0 to 1)\n- **P(A and B)**: Joint probability\n- **P(A or B)**: P(A) + P(B) - P(A and B)\n- **P(A|B)**: Conditional probability — P(A given B)\n- **Bayes Theorem**: P(A|B) = P(B|A) * P(A) / P(B)\n\n## Key Distributions\n\n- **Normal**: Bell curve. Mean=0, Std=1 (standard normal). 68-95-99.7 rule.\n- **Binomial**: Number of successes in n trials\n- **Poisson**: Number of events in a fixed interval\n- **Uniform**: Equal probability for all values\n\n## Hypothesis Testing\n\n1. State H0 (null) and H1 (alternative)\n2. Choose significance level alpha (usually 0.05)\n3. Calculate test statistic\n4. Find p-value\n5. If p < alpha: reject H0\n\n**Common tests:**\n- t-test: Compare means of two groups\n- Chi-square: Test independence of categorical variables\n- ANOVA: Compare means of 3+ groups\n- Correlation: Pearson (linear), Spearman (rank)\n\n```python\nfrom scipy import stats\n\n# t-test\nt_stat, p_value = stats.ttest_ind(group_a, group_b)\nprint(f't={t_stat:.3f}, p={p_value:.4f}')\n\n# Correlation\nr, p = stats.pearsonr(df['study_hours'], df['score'])\nprint(f'r={r:.3f}, p={p:.4f}')\n```\n\n## Practical Task\n\nUsing a dataset of exam scores: (1) Calculate all descriptive statistics. (2) Test whether students who studied 5+ hours scored significantly higher (t-test). (3) Check if gender and pass/fail are independent (chi-square). Report your findings with interpretation.\n\n## Self-Check\n1. When should you use median instead of mean?\n2. What does a p-value of 0.03 mean?\n3. What is the difference between correlation and causation?",
3,$ts);

ins_lesson($pdo,$lid,17,"Data Wrangling & Feature Engineering",
"## What is Data Wrangling?\n\nData wrangling (also called data munging) is the process of transforming raw, messy data into a clean, structured format suitable for analysis and modelling. Data scientists spend 60-80% of their time on this.\n\n## Common Data Quality Issues\n\n- Missing values (NaN, NULL, empty strings)\n- Duplicate records\n- Inconsistent formatting (dates, phone numbers, names)\n- Outliers and erroneous values\n- Wrong data types\n- Inconsistent categories (Male/male/M/m)\n\n## Handling Missing Values\n\n```python\n# Check missing\ndf.isnull().sum()\ndf.isnull().mean() * 100  # Percentage missing\n\n# Drop\ndf.dropna()                          # Drop any row with null\ndf.dropna(subset=['critical_col'])   # Drop only if critical col is null\ndf.dropna(thresh=5)                  # Keep rows with at least 5 non-null\n\n# Impute\ndf['age'].fillna(df['age'].median(), inplace=True)  # Median imputation\ndf['city'].fillna('Unknown', inplace=True)           # Constant\n\n# Advanced: KNN imputation\nfrom sklearn.impute import KNNImputer\nimputer = KNNImputer(n_neighbors=5)\ndf_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)\n```\n\n## Feature Engineering\n\nFeature engineering creates new variables that better represent the underlying patterns:\n\n```python\n# Date features\ndf['year']       = df['date'].dt.year\ndf['month']      = df['date'].dt.month\ndf['day_of_week']= df['date'].dt.dayofweek\ndf['is_weekend'] = df['day_of_week'].isin([5,6]).astype(int)\n\n# Binning\ndf['age_group'] = pd.cut(df['age'], bins=[0,18,35,60,100], labels=['Youth','Adult','Middle','Senior'])\n\n# Encoding categorical variables\ndf = pd.get_dummies(df, columns=['city'], drop_first=True)  # One-hot\ndf['gender_enc'] = df['gender'].map({'Male':1,'Female':0})   # Label\n\n# Scaling\nfrom sklearn.preprocessing import StandardScaler, MinMaxScaler\nscaler = StandardScaler()\ndf[['age','income']] = scaler.fit_transform(df[['age','income']])\n\n# Interaction features\ndf['income_per_age'] = df['income'] / (df['age'] + 1)\n```\n\n## Practical Task\n\nTake a messy dataset (create one with intentional issues: missing values, wrong types, duplicates, inconsistent categories). Perform a complete data wrangling pipeline: audit, clean, engineer 3 new features, encode categoricals, scale numerics. Document every decision.\n\n## Self-Check\n1. What is the difference between dropping and imputing missing values?\n2. Why do we scale features before modelling?\n3. What is one-hot encoding and when do you use it?",
4,$ts);

ins_lesson($pdo,$lid,17,"Machine Learning for Data Scientists",
"## ML in the Data Science Context\n\nData scientists use machine learning to build predictive models. This lesson covers the most important algorithms and when to use each.\n\n## Supervised Learning\n\n**Regression** (predict a continuous value):\n- Linear Regression: Assumes linear relationship\n- Ridge/Lasso: Linear with regularisation\n- Random Forest Regressor: Ensemble of decision trees\n- Gradient Boosting (XGBoost): State-of-the-art for tabular data\n\n**Classification** (predict a category):\n- Logistic Regression: Binary or multi-class\n- Decision Tree: Interpretable, prone to overfitting\n- Random Forest: Ensemble, robust\n- SVM: Effective in high dimensions\n- XGBoost/LightGBM: Best performance on structured data\n\n```python\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.metrics import classification_report\n\nX = df.drop('target', axis=1)\ny = df['target']\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nmodel = RandomForestClassifier(n_estimators=100, random_state=42)\nmodel.fit(X_train, y_train)\n\ny_pred = model.predict(X_test)\nprint(classification_report(y_test, y_pred))\n```\n\n## Model Evaluation\n\n**Classification metrics:**\n- Accuracy: Correct / Total (misleading with imbalanced data)\n- Precision: TP / (TP + FP)\n- Recall: TP / (TP + FN)\n- F1 Score: Harmonic mean of precision and recall\n- ROC-AUC: Area under the ROC curve\n\n**Regression metrics:**\n- MAE: Mean Absolute Error\n- RMSE: Root Mean Squared Error\n- R2: Proportion of variance explained\n\n## Cross-Validation\n\n```python\nfrom sklearn.model_selection import cross_val_score\nscores = cross_val_score(model, X, y, cv=5, scoring='f1_macro')\nprint(f'CV F1: {scores.mean():.3f} +/- {scores.std():.3f}')\n```\n\n## Practical Task\n\nBuild a student pass/fail prediction model. Features: study hours, attendance, previous scores, assignment completion. Use Random Forest. Evaluate with classification report and ROC-AUC. Identify the top 3 most important features.\n\n## Self-Check\n1. What is the difference between precision and recall?\n2. Why is accuracy a poor metric for imbalanced datasets?\n3. What is cross-validation and why is it important?",
5,$ts);

ins_lesson($pdo,$lid,17,"Data Visualisation & Storytelling",
"## Data Storytelling\n\nData storytelling is the ability to communicate insights from data using a combination of data, visualisations, and narrative. It is the most important skill for a data scientist working with non-technical stakeholders.\n\n## Choosing the Right Chart\n\n| Goal | Chart Type |\n|---|---|\n| Compare categories | Bar chart, Column chart |\n| Show trend over time | Line chart, Area chart |\n| Show distribution | Histogram, Box plot, Violin plot |\n| Show correlation | Scatter plot, Bubble chart |\n| Show proportions | Pie chart (max 5), Treemap |\n| Show geographic data | Choropleth map |\n| Show part-to-whole | Stacked bar, Waterfall |\n\n## Advanced Visualisation with Plotly\n\n```python\nimport plotly.express as px\nimport plotly.graph_objects as go\n\n# Interactive scatter\nfig = px.scatter(df, x='study_hours', y='score', color='grade',\n                 size='attendance', hover_data=['name'],\n                 title='Study Hours vs Score')\nfig.show()\n\n# Animated chart\nfig = px.bar(df_monthly, x='month', y='revenue', color='course',\n             animation_frame='year', title='Revenue by Course Over Time')\nfig.show()\n\n# Dashboard with subplots\nfrom plotly.subplots import make_subplots\nfig = make_subplots(rows=2, cols=2, subplot_titles=['Distribution','Trend','Correlation','Top 10'])\n```\n\n## Dashboard Tools\n\n- **Plotly Dash**: Python-based interactive dashboards\n- **Streamlit**: Fastest way to build data apps in Python\n- **Power BI**: Business intelligence, drag-and-drop\n- **Tableau**: Industry standard for visual analytics\n- **Google Looker Studio**: Free, connects to Google data\n\n## Streamlit Example\n\n```python\nimport streamlit as st\nimport pandas as pd\nimport plotly.express as px\n\nst.title('Student Performance Dashboard')\n\ndf = pd.read_csv('students.csv')\n\ncourse = st.selectbox('Select Course', df['course'].unique())\nfiltered = df[df['course'] == course]\n\ncol1, col2, col3 = st.columns(3)\ncol1.metric('Average Score', f\"{filtered['score'].mean():.1f}\")\ncol2.metric('Pass Rate', f\"{(filtered['score']>=50).mean()*100:.1f}%\")\ncol3.metric('Students', len(filtered))\n\nfig = px.histogram(filtered, x='score', title='Score Distribution')\nst.plotly_chart(fig)\n```\n\n## Practical Task\n\nBuild a Streamlit dashboard for a student performance dataset. Include: 3 KPI metrics, a score distribution chart, a trend over time, a top 10 students table, and a filter by course. Deploy locally and take a screenshot.\n\n## Self-Check\n1. What chart type is best for showing a trend over time?\n2. What is the difference between Plotly and Matplotlib?\n3. What is data storytelling and why does it matter?",
6,$ts);

ins_lesson($pdo,$lid,17,"Big Data & Cloud Data Science",
"## What is Big Data?\n\nBig Data refers to datasets too large or complex for traditional data processing tools. Characterised by the 5 Vs:\n\n- **Volume**: Terabytes to petabytes of data\n- **Velocity**: Data generated at high speed (real-time streams)\n- **Variety**: Structured, semi-structured, unstructured\n- **Veracity**: Uncertainty and quality of data\n- **Value**: The business value extracted from data\n\n## Big Data Technologies\n\n**Storage:**\n- Hadoop HDFS: Distributed file system\n- Amazon S3: Object storage in the cloud\n- Google Cloud Storage: GCP equivalent\n\n**Processing:**\n- Apache Spark: In-memory distributed processing (100x faster than Hadoop MapReduce)\n- Apache Kafka: Real-time data streaming\n- Apache Flink: Stream processing\n\n**Databases:**\n- MongoDB: Document store (JSON-like)\n- Cassandra: Wide-column store (high write throughput)\n- Redis: In-memory key-value store (caching)\n- BigQuery: Google's serverless data warehouse\n- Snowflake: Cloud data warehouse\n\n## PySpark Basics\n\n```python\nfrom pyspark.sql import SparkSession\n\nspark = SparkSession.builder.appName('DataScience').getOrCreate()\n\n# Load data\ndf = spark.read.csv('large_dataset.csv', header=True, inferSchema=True)\n\n# Operations (lazy evaluation)\ndf.filter(df['score'] > 70).groupBy('course').agg({'score': 'mean'}).show()\n\n# Convert to pandas for small results\npandas_df = df.toPandas()\n```\n\n## Cloud Data Science Platforms\n\n- **AWS SageMaker**: Build, train, deploy ML models at scale\n- **Google Vertex AI**: Unified ML platform on GCP\n- **Azure Machine Learning**: Microsoft's ML platform\n- **Databricks**: Unified analytics platform (Spark-based)\n- **Google Colab**: Free GPU/TPU notebooks\n\n## Practical Task\n\nCreate a free Google Colab notebook. Load a large dataset (1M+ rows) from Google Drive or BigQuery. Perform aggregations and visualisations. Compare the performance of pandas vs PySpark for the same operations.\n\n## Self-Check\n1. What are the 5 Vs of Big Data?\n2. What is the main advantage of Apache Spark over Hadoop MapReduce?\n3. Name 3 cloud data science platforms.",
7,$ts);

ins_lesson($pdo,$lid,17,"Capstone: End-to-End Data Science Project",
"## Final Project Brief\n\nYou will complete a full data science project from raw data to deployed model and dashboard.\n\n## Project Scenario\n\nYou are a data scientist at a Nigerian fintech company. The credit risk team wants a model to predict whether a loan applicant will default, and a dashboard for the risk team to monitor model performance.\n\n## Dataset\n\nCreate or download a loan dataset with features:\n- applicant_age, income, employment_years, loan_amount, loan_purpose\n- credit_score, existing_loans, education_level, state, gender\n- default (target: 0=no default, 1=default)\n\n## Phase 1: EDA & Data Quality\n- Descriptive statistics for all features\n- Missing value analysis and treatment\n- Outlier detection and handling\n- Distribution plots for all numeric features\n- Correlation analysis\n- Class imbalance check\n\n## Phase 2: Feature Engineering\n- Create debt-to-income ratio\n- Encode categorical variables\n- Scale numeric features\n- Handle class imbalance (SMOTE or class weights)\n- Feature selection (top 10 features by importance)\n\n## Phase 3: Modelling\n- Train 3 models: Logistic Regression, Random Forest, XGBoost\n- Cross-validate each model (5-fold)\n- Tune hyperparameters (GridSearchCV or RandomizedSearchCV)\n- Select best model based on ROC-AUC and F1\n\n## Phase 4: Evaluation & Interpretation\n- Confusion matrix\n- ROC curve and AUC\n- Feature importance plot\n- SHAP values for model explainability\n\n## Phase 5: Deployment\n- Save model with joblib or pickle\n- Build a Streamlit app: input applicant details, get default probability\n- Deploy to Streamlit Cloud (free)\n\n## Deliverables\n- Jupyter Notebook with complete analysis\n- Streamlit dashboard\n- 10-slide presentation with findings\n- 1-page executive summary\n\n## Evaluation Criteria\n- Data quality and EDA depth (20%)\n- Feature engineering creativity (15%)\n- Model performance (25%)\n- Code quality (20%)\n- Dashboard and presentation (20%)\n\n## Self-Check\n1. What metric would you prioritise for a fraud detection model and why?\n2. How would you explain your model's decision to a non-technical bank manager?\n3. What steps would you take if your model performs well in testing but poorly in production?",
8,$ts);

echo "Data Science lessons: done\n";

/*  ARTIFICIAL INTELLIGENCE (course_id=18)  */
ins_lesson($pdo,$lid,18,"Introduction to Artificial Intelligence",
"## What is Artificial Intelligence?\n\nArtificial Intelligence (AI) is the simulation of human intelligence processes by machines. These processes include learning, reasoning, problem-solving, perception, and language understanding.\n\n## Types of AI\n\n**By Capability:**\n- Narrow AI (ANI): Designed for one specific task (Siri, chess engines, spam filters)\n- General AI (AGI): Human-level intelligence across all domains (not yet achieved)\n- Super AI (ASI): Surpasses human intelligence in all areas (theoretical)\n\n**By Approach:**\n- Rule-based AI: Expert systems with hand-coded rules\n- Machine Learning: Learns patterns from data\n- Deep Learning: Neural networks with many layers\n- Generative AI: Creates new content (text, images, code)\n\n## AI History Timeline\n\n- 1950: Alan Turing proposes the Turing Test\n- 1956: Term AI coined at Dartmouth Conference\n- 1997: IBM Deep Blue beats chess world champion\n- 2012: Deep learning revolution (AlexNet wins ImageNet)\n- 2016: AlphaGo beats world Go champion\n- 2017: Transformer architecture introduced (Attention is All You Need)\n- 2022: ChatGPT launches, mainstream AI adoption begins\n- 2024: GPT-4o, Gemini, Claude 3  multimodal AI\n\n## AI Applications in Nigeria and Africa\n\n- Agriculture: Crop disease detection from smartphone photos\n- Healthcare: Malaria diagnosis from blood smear images\n- Finance: Fraud detection, credit scoring for the unbanked\n- Education: Personalised learning, automated grading\n- Language: NLP for Yoruba, Igbo, Hausa, Pidgin\n\n## Setting Up Your AI Environment\n\n```bash\npip install numpy pandas scikit-learn tensorflow torch transformers openai\n```\n\n## Practical Task\n\nResearch 3 AI applications currently being used in Nigerian companies or government. For each: describe the problem being solved, the AI approach used, and the impact. Write a 1-page report.\n\n## Self-Check\n1. What is the difference between Narrow AI and General AI?\n2. What was the significance of the 2012 AlexNet breakthrough?\n3. Name 3 AI applications relevant to the Nigerian context.",
1,$ts);

ins_lesson($pdo,$lid,18,"Machine Learning Foundations",
"## The Machine Learning Paradigm\n\nTraditional programming: Rules + Data = Output\nMachine Learning: Data + Output = Rules\n\nInstead of writing rules, we feed examples to an algorithm that learns the rules automatically.\n\n## Types of Machine Learning\n\n**Supervised Learning**: Learn from labelled examples\n- Classification: Predict a category (spam/not spam, disease/healthy)\n- Regression: Predict a number (house price, temperature)\n\n**Unsupervised Learning**: Find patterns in unlabelled data\n- Clustering: Group similar items (customer segments)\n- Dimensionality Reduction: Compress data (PCA, t-SNE)\n- Anomaly Detection: Find unusual patterns\n\n**Reinforcement Learning**: Learn by trial and error with rewards\n- Agent takes actions in an environment\n- Receives rewards or penalties\n- Learns optimal policy over time\n- Applications: Game playing, robotics, trading\n\n## The ML Workflow\n\n```python\nfrom sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.preprocessing import StandardScaler\nfrom sklearn.svm import SVC\nfrom sklearn.metrics import accuracy_score, classification_report\n\n# 1. Load data\nX, y = load_iris(return_X_y=True)\n\n# 2. Split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# 3. Preprocess\nscaler = StandardScaler()\nX_train = scaler.fit_transform(X_train)\nX_test = scaler.transform(X_test)\n\n# 4. Train\nmodel = SVC(kernel='rbf', C=1.0)\nmodel.fit(X_train, y_train)\n\n# 5. Evaluate\ny_pred = model.predict(X_test)\nprint(f'Accuracy: {accuracy_score(y_test, y_pred):.3f}')\nprint(classification_report(y_test, y_pred))\n```\n\n## Overfitting vs Underfitting\n\n- **Underfitting**: Model too simple, high bias, poor on training and test data\n- **Overfitting**: Model too complex, high variance, great on training but poor on test\n- **Good fit**: Low bias and low variance, generalises well\n\nSolutions:\n- Underfitting: More features, more complex model, more training\n- Overfitting: More data, regularisation, dropout, cross-validation\n\n## Practical Task\n\nBuild a spam email classifier using the SMS Spam Collection dataset from UCI. Try 3 algorithms: Naive Bayes, Logistic Regression, Random Forest. Compare accuracy, precision, recall, and F1. Which performs best and why?\n\n## Self-Check\n1. What is the difference between supervised and unsupervised learning?\n2. What is overfitting and how do you prevent it?\n3. What is the difference between classification and regression?",
2,$ts);

ins_lesson($pdo,$lid,18,"Neural Networks & Deep Learning",
"## What is a Neural Network?\n\nA neural network is a computational model inspired by the human brain. It consists of layers of interconnected nodes (neurons) that transform input data into output predictions.\n\n## Architecture\n\n- **Input Layer**: Receives raw features\n- **Hidden Layers**: Learn intermediate representations\n- **Output Layer**: Produces final prediction\n- **Weights**: Parameters learned during training\n- **Activation Functions**: Introduce non-linearity\n\n## Activation Functions\n\n- **ReLU**: max(0, x)  most common for hidden layers\n- **Sigmoid**: 1/(1+e^-x)  binary classification output\n- **Softmax**: Multi-class classification output\n- **Tanh**: Range -1 to 1, used in RNNs\n\n## Building a Neural Network with TensorFlow/Keras\n\n```python\nimport tensorflow as tf\nfrom tensorflow import keras\nimport numpy as np\n\n# Load MNIST handwritten digits\n(X_train, y_train), (X_test, y_test) = keras.datasets.mnist.load_data()\n\n# Preprocess\nX_train = X_train.reshape(-1, 784) / 255.0\nX_test  = X_test.reshape(-1, 784) / 255.0\n\n# Build model\nmodel = keras.Sequential([\n    keras.layers.Dense(256, activation='relu', input_shape=(784,)),\n    keras.layers.Dropout(0.3),\n    keras.layers.Dense(128, activation='relu'),\n    keras.layers.Dropout(0.3),\n    keras.layers.Dense(10, activation='softmax')\n])\n\n# Compile\nmodel.compile(\n    optimizer='adam',\n    loss='sparse_categorical_crossentropy',\n    metrics=['accuracy']\n)\n\n# Train\nhistory = model.fit(X_train, y_train, epochs=10, batch_size=32,\n                    validation_split=0.1, verbose=1)\n\n# Evaluate\ntest_loss, test_acc = model.evaluate(X_test, y_test)\nprint(f'Test accuracy: {test_acc:.4f}')\n```\n\n## Backpropagation\n\nBackpropagation is the algorithm that trains neural networks:\n1. Forward pass: Compute predictions\n2. Calculate loss (error)\n3. Backward pass: Compute gradients using chain rule\n4. Update weights: w = w - learning_rate * gradient\n\n## Practical Task\n\nBuild a neural network to classify handwritten digits (MNIST). Experiment with: number of layers, number of neurons, dropout rates, and learning rates. Plot training and validation accuracy curves. Achieve at least 98% test accuracy.\n\n## Self-Check\n1. What is the role of activation functions in neural networks?\n2. What is dropout and why does it help prevent overfitting?\n3. Explain backpropagation in simple terms.",
3,$ts);

ins_lesson($pdo,$lid,18,"Computer Vision with CNNs",
"## What is Computer Vision?\n\nComputer vision enables machines to interpret and understand visual information from images and videos. It is one of the most successful applications of deep learning.\n\n## Convolutional Neural Networks (CNNs)\n\nCNNs are designed specifically for image data. They use convolutional layers to automatically learn spatial features.\n\n**Key Components:**\n- **Convolutional Layer**: Applies filters to detect features (edges, textures, shapes)\n- **Pooling Layer**: Reduces spatial dimensions (Max Pooling, Average Pooling)\n- **Flatten Layer**: Converts 2D feature maps to 1D vector\n- **Dense Layer**: Final classification\n\n```python\nimport tensorflow as tf\nfrom tensorflow import keras\n\n# CNN for image classification\nmodel = keras.Sequential([\n    # Block 1\n    keras.layers.Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),\n    keras.layers.MaxPooling2D(2,2),\n\n    # Block 2\n    keras.layers.Conv2D(64, (3,3), activation='relu'),\n    keras.layers.MaxPooling2D(2,2),\n\n    # Block 3\n    keras.layers.Conv2D(128, (3,3), activation='relu'),\n    keras.layers.MaxPooling2D(2,2),\n\n    # Classifier\n    keras.layers.Flatten(),\n    keras.layers.Dense(512, activation='relu'),\n    keras.layers.Dropout(0.5),\n    keras.layers.Dense(10, activation='softmax')\n])\n```\n\n## Transfer Learning\n\nTransfer learning uses a pre-trained model (trained on millions of images) as a starting point:\n\n```python\n# Use VGG16 pre-trained on ImageNet\nbase_model = keras.applications.VGG16(weights='imagenet', include_top=False, input_shape=(224,224,3))\nbase_model.trainable = False  # Freeze base layers\n\nmodel = keras.Sequential([\n    base_model,\n    keras.layers.GlobalAveragePooling2D(),\n    keras.layers.Dense(256, activation='relu'),\n    keras.layers.Dense(num_classes, activation='softmax')\n])\n```\n\nPopular pre-trained models: VGG16, ResNet50, InceptionV3, EfficientNet, MobileNet\n\n## Real-World Applications\n\n- Medical imaging: Detect malaria, tuberculosis, cancer from scans\n- Agriculture: Identify crop diseases from leaf photos\n- Security: Face recognition, object detection\n- Autonomous vehicles: Lane detection, pedestrian detection\n- Quality control: Defect detection in manufacturing\n\n## Practical Task\n\nBuild a crop disease classifier using transfer learning (MobileNetV2). Dataset: PlantVillage (available on Kaggle). Train to classify 5 disease types. Achieve 90%+ validation accuracy. Build a simple web interface where a farmer can upload a leaf photo and get a diagnosis.\n\n## Self-Check\n1. What is the purpose of a convolutional layer?\n2. What is transfer learning and why is it useful?\n3. Name 3 real-world applications of computer vision in Africa.",
4,$ts);

ins_lesson($pdo,$lid,18,"Natural Language Processing (NLP)",
"## What is NLP?\n\nNatural Language Processing (NLP) enables computers to understand, interpret, and generate human language. It bridges the gap between human communication and computer understanding.\n\n## NLP Pipeline\n\n1. **Text Preprocessing**: Tokenisation, lowercasing, punctuation removal\n2. **Stop Word Removal**: Remove common words (the, is, at)\n3. **Stemming/Lemmatisation**: Reduce words to root form\n4. **Feature Extraction**: Convert text to numbers\n5. **Modelling**: Apply ML/DL model\n6. **Post-processing**: Interpret and format output\n\n## Text Preprocessing\n\n```python\nimport re\nimport nltk\nfrom nltk.tokenize import word_tokenize\nfrom nltk.corpus import stopwords\nfrom nltk.stem import WordNetLemmatizer\n\nnltk.download(['punkt','stopwords','wordnet'])\n\ndef preprocess(text):\n    text = text.lower()\n    text = re.sub(r'[^a-z0-9\\s]', '', text)\n    tokens = word_tokenize(text)\n    stop_words = set(stopwords.words('english'))\n    tokens = [t for t in tokens if t not in stop_words]\n    lemmatizer = WordNetLemmatizer()\n    tokens = [lemmatizer.lemmatize(t) for t in tokens]\n    return ' '.join(tokens)\n```\n\n## Text Vectorisation\n\n```python\nfrom sklearn.feature_extraction.text import TfidfVectorizer\nfrom sklearn.linear_model import LogisticRegression\n\n# TF-IDF\nvectorizer = TfidfVectorizer(max_features=5000, ngram_range=(1,2))\nX_train_vec = vectorizer.fit_transform(X_train)\nX_test_vec  = vectorizer.transform(X_test)\n\nmodel = LogisticRegression()\nmodel.fit(X_train_vec, y_train)\n```\n\n## Transformers & BERT\n\n```python\nfrom transformers import pipeline\n\n# Sentiment analysis\nsentiment = pipeline('sentiment-analysis')\nresult = sentiment('This course is absolutely amazing!')\nprint(result)  # [{'label': 'POSITIVE', 'score': 0.9998}]\n\n# Text generation\ngenerator = pipeline('text-generation', model='gpt2')\nresult = generator('The future of AI in Nigeria is', max_length=100)\n\n# Named Entity Recognition\nner = pipeline('ner', grouped_entities=True)\nresult = ner('Dangote Group is headquartered in Lagos, Nigeria.')\n```\n\n## NLP for African Languages\n\nChallenges: Low-resource languages, tonal languages, code-switching (mixing languages)\n\nProjects:\n- Masakhane: NLP for African languages (masakhane.io)\n- AfriSenti: Sentiment analysis for African languages\n- Yoruba, Hausa, Igbo NLP datasets on HuggingFace\n\n## Practical Task\n\nBuild a sentiment analyser for Nigerian social media comments (Twitter/X). Collect 500 comments about a Nigerian brand. Preprocess the text. Train a classifier (Logistic Regression + TF-IDF). Evaluate with F1 score. Identify the top positive and negative themes.\n\n## Self-Check\n1. What is the difference between stemming and lemmatisation?\n2. What is TF-IDF and why is it better than simple word counts?\n3. What is a Transformer model and what problem does it solve?",
5,$ts);

ins_lesson($pdo,$lid,18,"Generative AI & Large Language Models",
"## What is Generative AI?\n\nGenerative AI creates new content  text, images, audio, video, code  that did not exist before. It is powered by large models trained on massive datasets.\n\n## Large Language Models (LLMs)\n\nLLMs are neural networks trained on billions of text tokens. They learn to predict the next token, which enables them to generate coherent text.\n\n**Key LLMs:**\n- GPT-4o / GPT-5 (OpenAI): Most capable general-purpose LLM\n- Claude 3.5 (Anthropic): Strong reasoning and safety\n- Gemini 1.5 (Google): Multimodal, long context\n- Llama 3 (Meta): Open-source, can run locally\n- Mistral: Efficient open-source models\n\n## The Transformer Architecture\n\nThe Transformer (2017) revolutionised AI:\n- **Self-Attention**: Each token attends to all other tokens\n- **Multi-Head Attention**: Multiple attention patterns in parallel\n- **Positional Encoding**: Encodes token position\n- **Feed-Forward Layers**: Process attended representations\n\n## Using OpenAI API\n\n```python\nfrom openai import OpenAI\n\nclient = OpenAI(api_key='your-api-key')\n\n# Chat completion\nresponse = client.chat.completions.create(\n    model='gpt-4o-mini',\n    messages=[\n        {'role': 'system', 'content': 'You are a helpful tutor for Nigerian students.'},\n        {'role': 'user', 'content': 'Explain machine learning in simple terms.'}\n    ],\n    max_tokens=500\n)\nprint(response.choices[0].message.content)\n\n# With the Responses API (newer)\nresponse = client.responses.create(\n    model='gpt-5-nano',\n    instructions='You are a helpful tutor.',\n    input='Explain neural networks to a beginner.'\n)\nprint(response.output_text)\n```\n\n## Prompt Engineering\n\nThe art of crafting effective prompts:\n\n- **Zero-shot**: Ask directly without examples\n- **Few-shot**: Provide 2-3 examples before the question\n- **Chain-of-thought**: Ask the model to think step by step\n- **Role prompting**: Assign a persona (You are an expert...)\n- **Structured output**: Ask for JSON, tables, or specific formats\n\n## RAG (Retrieval-Augmented Generation)\n\nRAG combines LLMs with a knowledge base:\n1. Store documents in a vector database (Pinecone, ChromaDB)\n2. Convert query to embedding\n3. Retrieve most similar documents\n4. Feed documents + query to LLM\n5. LLM generates answer grounded in your documents\n\n## Practical Task\n\nBuild an AI tutor chatbot for one of your courses using the OpenAI API. Features: (1) Answer questions about the course content, (2) Generate practice questions, (3) Explain concepts at different difficulty levels. Use prompt engineering to make it course-specific.\n\n## Self-Check\n1. What is the key innovation of the Transformer architecture?\n2. What is prompt engineering and why does it matter?\n3. What is RAG and when would you use it instead of fine-tuning?",
6,$ts);

ins_lesson($pdo,$lid,18,"AI Ethics, Safety & Responsible AI",
"## Why AI Ethics Matters\n\nAI systems can cause significant harm if not designed and deployed responsibly. As AI becomes more powerful and widespread, ethical considerations become critical.\n\n## Key AI Ethics Principles\n\n**Fairness**: AI should not discriminate based on race, gender, religion, or other protected characteristics.\n\n**Transparency**: Users should understand how AI makes decisions (explainability).\n\n**Accountability**: Someone must be responsible when AI causes harm.\n\n**Privacy**: AI should not violate users' privacy or misuse personal data.\n\n**Safety**: AI systems should be reliable and not cause unintended harm.\n\n**Beneficence**: AI should benefit humanity, not just its creators.\n\n## AI Bias\n\nBias in AI comes from biased training data or biased model design:\n\n- **Historical bias**: Training data reflects past discrimination\n- **Representation bias**: Underrepresented groups in training data\n- **Measurement bias**: Proxy variables that correlate with protected attributes\n- **Aggregation bias**: One model for diverse populations\n\n**Example**: A hiring AI trained on historical data may discriminate against women if historically fewer women were hired.\n\n## Detecting and Mitigating Bias\n\n```python\nfrom sklearn.metrics import classification_report\nimport pandas as pd\n\n# Check performance by demographic group\nfor group in df['gender'].unique():\n    mask = df['gender'] == group\n    print(f'\\n--- {group} ---')\n    print(classification_report(y_test[mask], y_pred[mask]))\n\n# Fairness metrics\nfrom fairlearn.metrics import demographic_parity_difference, equalized_odds_difference\ndpd = demographic_parity_difference(y_test, y_pred, sensitive_features=df['gender'])\nprint(f'Demographic Parity Difference: {dpd:.3f}')\n```\n\n## AI Safety\n\n- **Alignment**: Ensuring AI pursues human-intended goals\n- **Robustness**: AI should work reliably in unexpected situations\n- **Adversarial attacks**: Inputs designed to fool AI models\n- **Hallucination**: LLMs generating false but confident information\n\n## AI Regulation\n\n- EU AI Act (2024): Risk-based regulation of AI systems\n- Nigeria: NITDA AI Policy Framework\n- US: Executive Order on AI Safety\n\n## Practical Task\n\nAudit a machine learning model for bias. Train a loan approval model. Check if the model has different approval rates for different demographic groups. Calculate fairness metrics. Propose 3 specific interventions to reduce bias. Write a 2-page responsible AI report.\n\n## Self-Check\n1. What is algorithmic bias and how does it arise?\n2. What is the difference between AI safety and AI ethics?\n3. What is the EU AI Act and what does it regulate?",
7,$ts);

ins_lesson($pdo,$lid,18,"Capstone: AI Application Project",
"## Final Project Brief\n\nYou will design and build a complete AI application that solves a real problem relevant to Nigeria or Africa.\n\n## Project Options (Choose One)\n\n### Option A: AI Health Assistant\nA chatbot that helps Nigerians understand medical symptoms and find nearby healthcare facilities.\n- NLP for symptom extraction from natural language\n- Medical knowledge base (RAG)\n- Multilingual support (English + Pidgin)\n- Integration with Google Maps API for facility lookup\n\n### Option B: Agricultural AI Advisor\nAn AI system that helps Nigerian farmers make better decisions.\n- Crop disease detection from photos (CNN)\n- Weather-based planting recommendations\n- Market price prediction (time series)\n- Voice interface in Hausa or Yoruba\n\n### Option C: Financial Inclusion AI\nAn AI system for credit scoring of unbanked Nigerians.\n- Alternative data features (mobile money, airtime usage)\n- Fairness-aware model (no discrimination by ethnicity/gender)\n- Explainable AI (SHAP values for each decision)\n- Simple mobile interface\n\n## Technical Requirements\n\n- At least 2 AI/ML components (e.g. NLP + classification)\n- Training data: minimum 1,000 examples\n- Model evaluation with appropriate metrics\n- Bias audit with fairness metrics\n- Deployed application (Streamlit, Flask, or mobile)\n- API integration (OpenAI, Google, or similar)\n\n## Deliverables\n\n1. GitHub repository with clean, documented code\n2. Jupyter Notebook with model development\n3. Deployed application (live URL)\n4. 15-minute demo presentation\n5. Technical report (5 pages)\n6. Ethical impact assessment\n\n## Evaluation Criteria\n- Problem relevance and impact (20%)\n- Technical implementation quality (30%)\n- Model performance (20%)\n- Responsible AI practices (15%)\n- Presentation and documentation (15%)\n\n## Self-Check\n1. Does your application solve a real problem for real people?\n2. Have you tested your model for bias and fairness?\n3. Can a non-technical user understand and use your application?",
8,$ts);

echo "AI lessons: done\n";

/* ── MACHINE LEARNING (course_id=19) ── */
ins_lesson($pdo,$lid,19,"Introduction to Machine Learning",
"## What is Machine Learning?\n\nMachine Learning is a subset of AI that enables systems to learn and improve from experience without being explicitly programmed. Instead of writing rules, you provide data and the algorithm discovers the rules.\n\n## Why Machine Learning Now?\n\n- **Data explosion**: Smartphones, IoT, social media generate massive data\n- **Computing power**: GPUs make training large models feasible\n- **Algorithm advances**: Better architectures and optimisation methods\n- **Open source**: TensorFlow, PyTorch, scikit-learn freely available\n\n## The ML Landscape\n\n```\nArtificial Intelligence\n  Machine Learning\n    Supervised Learning\n      Classification\n      Regression\n    Unsupervised Learning\n      Clustering\n      Dimensionality Reduction\n    Semi-supervised Learning\n    Self-supervised Learning\n  Deep Learning\n    CNNs (images)\n    RNNs/LSTMs (sequences)\n    Transformers (text, multimodal)\n  Reinforcement Learning\n```\n\n## Setting Up the ML Environment\n\n```bash\n# Create virtual environment\npython -m venv ml_env\nsource ml_env/bin/activate  # Linux/Mac\nml_env\\Scripts\\activate     # Windows\n\n# Install core libraries\npip install numpy pandas scikit-learn matplotlib seaborn\npip install tensorflow torch torchvision\npip install xgboost lightgbm catboost\npip install jupyter notebook\n```\n\n## Your First ML Model\n\n```python\nfrom sklearn.datasets import load_breast_cancer\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import accuracy_score\n\n# Load data\ndata = load_breast_cancer()\nX, y = data.data, data.target\n\n# Split\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Train\nmodel = LogisticRegression(max_iter=10000)\nmodel.fit(X_train, y_train)\n\n# Predict and evaluate\ny_pred = model.predict(X_test)\nprint(f'Accuracy: {accuracy_score(y_test, y_pred):.4f}')\n```\n\n## Practical Task\n\nBuild your first ML model to predict whether a student will pass or fail based on: study hours, attendance percentage, assignment completion rate, and previous test scores. Use Logistic Regression. Report accuracy, precision, and recall.\n\n## Self-Check\n1. What is the difference between AI and Machine Learning?\n2. Name the 3 main types of machine learning.\n3. What is the purpose of splitting data into training and test sets?",
1,$ts);

ins_lesson($pdo,$lid,19,"Supervised Learning: Regression",
"## Regression Algorithms\n\nRegression predicts a continuous numerical value. It answers: How much? How many? What price?\n\n## Linear Regression\n\nAssumes a linear relationship between features and target:\ny = w0 + w1*x1 + w2*x2 + ... + wn*xn\n\n```python\nfrom sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet\nfrom sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score\nimport numpy as np\n\n# Simple linear regression\nmodel = LinearRegression()\nmodel.fit(X_train, y_train)\ny_pred = model.predict(X_test)\n\nprint(f'MAE:  {mean_absolute_error(y_test, y_pred):.2f}')\nprint(f'RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.2f}')\nprint(f'R2:   {r2_score(y_test, y_pred):.4f}')\nprint(f'Coefficients: {model.coef_}')\n\n# Regularised regression\nridge = Ridge(alpha=1.0)      # L2 regularisation\nlasso = Lasso(alpha=0.1)      # L1 regularisation (feature selection)\nelastic = ElasticNet(alpha=0.1, l1_ratio=0.5)  # L1 + L2\n```\n\n## Polynomial Regression\n\n```python\nfrom sklearn.preprocessing import PolynomialFeatures\nfrom sklearn.pipeline import Pipeline\n\npoly_model = Pipeline([\n    ('poly', PolynomialFeatures(degree=2)),\n    ('linear', LinearRegression())\n])\npoly_model.fit(X_train, y_train)\n```\n\n## Gradient Boosting Regression\n\n```python\nimport xgboost as xgb\nfrom sklearn.model_selection import GridSearchCV\n\nxgb_model = xgb.XGBRegressor(\n    n_estimators=100,\n    learning_rate=0.1,\n    max_depth=6,\n    random_state=42\n)\n\n# Hyperparameter tuning\nparam_grid = {\n    'n_estimators': [100, 200],\n    'learning_rate': [0.05, 0.1],\n    'max_depth': [4, 6, 8]\n}\ngrid_search = GridSearchCV(xgb_model, param_grid, cv=5, scoring='r2')\ngrid_search.fit(X_train, y_train)\nprint(f'Best params: {grid_search.best_params_}')\nprint(f'Best R2: {grid_search.best_score_:.4f}')\n```\n\n## Regression Metrics\n\n- **MAE**: Mean Absolute Error — average absolute difference\n- **RMSE**: Root Mean Squared Error — penalises large errors more\n- **R2**: Proportion of variance explained (1.0 = perfect)\n- **MAPE**: Mean Absolute Percentage Error — interpretable as %\n\n## Practical Task\n\nBuild a house price prediction model for Lagos properties. Features: size (sqm), bedrooms, bathrooms, location (island/mainland/suburb), age, parking spaces. Compare Linear Regression, Ridge, and XGBoost. Use RMSE and R2 as metrics. Identify the most important features.\n\n## Self-Check\n1. What is the difference between MAE and RMSE?\n2. What is regularisation and why is it needed?\n3. When would you use Lasso over Ridge regression?",
2,$ts);

ins_lesson($pdo,$lid,19,"Supervised Learning: Classification",
"## Classification Algorithms\n\nClassification predicts which category an input belongs to. Binary (2 classes) or multi-class (3+ classes).\n\n## Logistic Regression\n\nDespite the name, it is a classification algorithm. Uses sigmoid function to output probabilities.\n\n```python\nfrom sklearn.linear_model import LogisticRegression\nfrom sklearn.metrics import classification_report, confusion_matrix, roc_auc_score\nimport seaborn as sns\n\nmodel = LogisticRegression(C=1.0, max_iter=1000)\nmodel.fit(X_train, y_train)\n\ny_pred = model.predict(X_test)\ny_prob = model.predict_proba(X_test)[:, 1]\n\nprint(classification_report(y_test, y_pred))\nprint(f'ROC-AUC: {roc_auc_score(y_test, y_prob):.4f}')\n\n# Confusion matrix\ncm = confusion_matrix(y_test, y_pred)\nsns.heatmap(cm, annot=True, fmt='d', cmap='Blues')\n```\n\n## Decision Trees & Random Forest\n\n```python\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Decision Tree\ndt = DecisionTreeClassifier(max_depth=5, min_samples_leaf=10)\ndt.fit(X_train, y_train)\n\n# Random Forest (ensemble of trees)\nrf = RandomForestClassifier(\n    n_estimators=200,\n    max_depth=10,\n    min_samples_leaf=5,\n    n_jobs=-1,\n    random_state=42\n)\nrf.fit(X_train, y_train)\n\n# Feature importance\nimportances = pd.Series(rf.feature_importances_, index=feature_names)\nimportances.sort_values().plot(kind='barh')\n```\n\n## XGBoost — State of the Art\n\n```python\nimport xgboost as xgb\n\nmodel = xgb.XGBClassifier(\n    n_estimators=300,\n    learning_rate=0.05,\n    max_depth=6,\n    subsample=0.8,\n    colsample_bytree=0.8,\n    use_label_encoder=False,\n    eval_metric='logloss',\n    random_state=42\n)\nmodel.fit(X_train, y_train,\n          eval_set=[(X_test, y_test)],\n          early_stopping_rounds=20,\n          verbose=False)\n```\n\n## Handling Imbalanced Classes\n\n```python\nfrom imblearn.over_sampling import SMOTE\nfrom imblearn.pipeline import Pipeline\n\n# SMOTE: Synthetic Minority Over-sampling\nsmote = SMOTE(random_state=42)\nX_resampled, y_resampled = smote.fit_resample(X_train, y_train)\n\n# Or use class_weight\nmodel = RandomForestClassifier(class_weight='balanced')\n```\n\n## Practical Task\n\nBuild a fraud detection model for mobile money transactions. Dataset: create synthetic data with features (amount, time_of_day, merchant_type, location_change, device_change). Handle class imbalance (fraud is rare). Compare models. Optimise for recall (catching fraud is more important than false alarms).\n\n## Self-Check\n1. What is the difference between precision and recall? Which matters more for fraud detection?\n2. What is a Random Forest and how does it differ from a single Decision Tree?\n3. What is SMOTE and when do you use it?",
3,$ts);

ins_lesson($pdo,$lid,19,"Unsupervised Learning",
"## What is Unsupervised Learning?\n\nUnsupervised learning finds hidden patterns in data without labelled examples. The algorithm discovers structure on its own.\n\n## Clustering\n\nClustering groups similar data points together.\n\n### K-Means Clustering\n\n```python\nfrom sklearn.cluster import KMeans\nfrom sklearn.preprocessing import StandardScaler\nimport matplotlib.pyplot as plt\n\n# Scale features\nscaler = StandardScaler()\nX_scaled = scaler.fit_transform(X)\n\n# Find optimal k using elbow method\ninertias = []\nfor k in range(1, 11):\n    km = KMeans(n_clusters=k, random_state=42, n_init=10)\n    km.fit(X_scaled)\n    inertias.append(km.inertia_)\n\nplt.plot(range(1,11), inertias, 'bo-')\nplt.xlabel('Number of clusters')\nplt.ylabel('Inertia')\nplt.title('Elbow Method')\nplt.show()\n\n# Fit with optimal k\nkm = KMeans(n_clusters=4, random_state=42, n_init=10)\ndf['cluster'] = km.fit_predict(X_scaled)\n```\n\n### DBSCAN — Density-Based Clustering\n\n```python\nfrom sklearn.cluster import DBSCAN\n\n# Good for non-spherical clusters and outlier detection\ndbscan = DBSCAN(eps=0.5, min_samples=5)\ndf['cluster'] = dbscan.fit_predict(X_scaled)\n# Cluster -1 = outliers/noise\n```\n\n## Dimensionality Reduction\n\n### PCA — Principal Component Analysis\n\n```python\nfrom sklearn.decomposition import PCA\n\n# Reduce to 2D for visualisation\npca = PCA(n_components=2)\nX_2d = pca.fit_transform(X_scaled)\n\nprint(f'Explained variance: {pca.explained_variance_ratio_}')\nprint(f'Total variance retained: {pca.explained_variance_ratio_.sum():.3f}')\n\nplt.scatter(X_2d[:,0], X_2d[:,1], c=y, cmap='viridis')\nplt.xlabel('PC1')\nplt.ylabel('PC2')\n```\n\n### t-SNE — For Visualisation\n\n```python\nfrom sklearn.manifold import TSNE\n\ntsne = TSNE(n_components=2, perplexity=30, random_state=42)\nX_tsne = tsne.fit_transform(X_scaled)\n\nplt.scatter(X_tsne[:,0], X_tsne[:,1], c=y, cmap='tab10')\n```\n\n## Anomaly Detection\n\n```python\nfrom sklearn.ensemble import IsolationForest\n\niso = IsolationForest(contamination=0.05, random_state=42)\ndf['anomaly'] = iso.fit_predict(X_scaled)\n# -1 = anomaly, 1 = normal\n```\n\n## Practical Task\n\nPerform customer segmentation for a Nigerian e-commerce company. Features: purchase frequency, average order value, days since last purchase, product categories. Use K-Means (find optimal k). Visualise with PCA. Name each segment and write a marketing strategy for each.\n\n## Self-Check\n1. What is the difference between K-Means and DBSCAN?\n2. What does PCA do and why is it useful?\n3. What is anomaly detection and give a real-world use case?",
4,$ts);

ins_lesson($pdo,$lid,19,"Model Evaluation & Hyperparameter Tuning",
"## Why Model Evaluation Matters\n\nA model that performs well on training data but poorly on new data is useless. Proper evaluation ensures your model generalises.\n\n## Train/Validation/Test Split\n\n```python\nfrom sklearn.model_selection import train_test_split\n\n# First split: 80% train+val, 20% test\nX_trainval, X_test, y_trainval, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\n# Second split: 75% train, 25% val (of the 80%)\nX_train, X_val, y_train, y_val = train_test_split(X_trainval, y_trainval, test_size=0.25, random_state=42)\n\n# Result: 60% train, 20% val, 20% test\n```\n\n## Cross-Validation\n\n```python\nfrom sklearn.model_selection import cross_val_score, StratifiedKFold\n\n# 5-fold stratified cross-validation\ncv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)\nscores = cross_val_score(model, X, y, cv=cv, scoring='f1_macro')\nprint(f'CV F1: {scores.mean():.4f} +/- {scores.std():.4f}')\n```\n\n## Hyperparameter Tuning\n\n### Grid Search\n\n```python\nfrom sklearn.model_selection import GridSearchCV\n\nparam_grid = {\n    'n_estimators': [100, 200, 300],\n    'max_depth': [4, 6, 8, None],\n    'min_samples_leaf': [1, 5, 10]\n}\n\ngrid = GridSearchCV(RandomForestClassifier(random_state=42),\n                    param_grid, cv=5, scoring='f1_macro',\n                    n_jobs=-1, verbose=1)\ngrid.fit(X_train, y_train)\nprint(f'Best: {grid.best_params_}, Score: {grid.best_score_:.4f}')\n```\n\n### Optuna — Bayesian Optimisation\n\n```python\nimport optuna\n\ndef objective(trial):\n    params = {\n        'n_estimators': trial.suggest_int('n_estimators', 50, 500),\n        'max_depth': trial.suggest_int('max_depth', 3, 12),\n        'learning_rate': trial.suggest_float('learning_rate', 0.01, 0.3, log=True),\n    }\n    model = xgb.XGBClassifier(**params, random_state=42)\n    score = cross_val_score(model, X_train, y_train, cv=5, scoring='roc_auc').mean()\n    return score\n\nstudy = optuna.create_study(direction='maximize')\nstudy.optimize(objective, n_trials=100)\nprint(f'Best params: {study.best_params}')\n```\n\n## Learning Curves\n\n```python\nfrom sklearn.model_selection import learning_curve\n\ntrain_sizes, train_scores, val_scores = learning_curve(\n    model, X, y, cv=5, n_jobs=-1,\n    train_sizes=np.linspace(0.1, 1.0, 10)\n)\n\nplt.plot(train_sizes, train_scores.mean(axis=1), label='Training')\nplt.plot(train_sizes, val_scores.mean(axis=1), label='Validation')\nplt.xlabel('Training size')\nplt.ylabel('Score')\nplt.legend()\n```\n\n## Practical Task\n\nTake your fraud detection model from Lesson 3. Tune it using Optuna (100 trials). Plot learning curves to diagnose overfitting/underfitting. Compare the tuned vs untuned model. Report the improvement in ROC-AUC.\n\n## Self-Check\n1. What is the difference between Grid Search and Bayesian Optimisation?\n2. What do learning curves tell you about your model?\n3. Why should you never tune hyperparameters on the test set?",
5,$ts);

ins_lesson($pdo,$lid,19,"Feature Engineering & Selection",
"## Feature Engineering\n\nFeature engineering is the process of using domain knowledge to create features that make ML algorithms work better. It is often the difference between a mediocre and an excellent model.\n\n## Feature Creation Techniques\n\n```python\nimport pandas as pd\nimport numpy as np\n\n# Interaction features\ndf['income_to_loan_ratio'] = df['income'] / (df['loan_amount'] + 1)\ndf['age_times_experience'] = df['age'] * df['work_experience']\n\n# Polynomial features\nfrom sklearn.preprocessing import PolynomialFeatures\npoly = PolynomialFeatures(degree=2, include_bias=False)\nX_poly = poly.fit_transform(X[['age', 'income']])\n\n# Aggregation features (for grouped data)\ndf['avg_score_by_course'] = df.groupby('course')['score'].transform('mean')\ndf['rank_in_course'] = df.groupby('course')['score'].rank(ascending=False)\n\n# Time-based features\ndf['hour'] = df['timestamp'].dt.hour\ndf['is_business_hours'] = df['hour'].between(9, 17).astype(int)\ndf['days_since_registration'] = (pd.Timestamp.now() - df['reg_date']).dt.days\n\n# Text features\ndf['name_length'] = df['name'].str.len()\ndf['word_count'] = df['description'].str.split().str.len()\n```\n\n## Feature Selection\n\nToo many features cause overfitting and slow training. Select only the most informative ones.\n\n```python\nfrom sklearn.feature_selection import SelectKBest, f_classif, RFE, mutual_info_classif\nfrom sklearn.ensemble import RandomForestClassifier\n\n# Filter method: Statistical test\nselector = SelectKBest(f_classif, k=10)\nX_selected = selector.fit_transform(X, y)\nselected_features = X.columns[selector.get_support()]\n\n# Wrapper method: Recursive Feature Elimination\nrfe = RFE(RandomForestClassifier(n_estimators=50), n_features_to_select=10)\nrfe.fit(X_train, y_train)\nprint(X.columns[rfe.support_])\n\n# Embedded method: Feature importance from tree models\nrf = RandomForestClassifier(n_estimators=100)\nrf.fit(X_train, y_train)\nimportances = pd.Series(rf.feature_importances_, index=X.columns)\ntop_features = importances.nlargest(10).index\n\n# SHAP values for model-agnostic importance\nimport shap\nexplainer = shap.TreeExplainer(rf)\nshap_values = explainer.shap_values(X_test)\nshap.summary_plot(shap_values[1], X_test)\n```\n\n## Practical Task\n\nTake a dataset with 50+ features. Apply feature engineering to create 10 new features. Use 3 different feature selection methods. Compare model performance with: all features, top 10 by importance, top 10 by RFE. Which approach gives the best result?\n\n## Self-Check\n1. What is the difference between filter, wrapper, and embedded feature selection methods?\n2. What are SHAP values and why are they useful?\n3. Why can too many features hurt model performance?",
6,$ts);

ins_lesson($pdo,$lid,19,"ML Deployment & MLOps",
"## What is MLOps?\n\nMLOps (Machine Learning Operations) is the practice of deploying, monitoring, and maintaining ML models in production. It bridges the gap between data science and software engineering.\n\n## Saving and Loading Models\n\n```python\nimport joblib\nimport pickle\n\n# Save with joblib (recommended for scikit-learn)\njoblib.dump(model, 'model.joblib')\njoblib.dump(scaler, 'scaler.joblib')\n\n# Load\nmodel = joblib.load('model.joblib')\nscaler = joblib.load('scaler.joblib')\n\n# Save with pickle\nwith open('model.pkl', 'wb') as f:\n    pickle.dump(model, f)\n```\n\n## Building a REST API with Flask\n\n```python\nfrom flask import Flask, request, jsonify\nimport joblib\nimport numpy as np\n\napp = Flask(__name__)\nmodel = joblib.load('model.joblib')\nscaler = joblib.load('scaler.joblib')\n\n@app.route('/predict', methods=['POST'])\ndef predict():\n    data = request.get_json()\n    features = np.array(data['features']).reshape(1, -1)\n    features_scaled = scaler.transform(features)\n    prediction = model.predict(features_scaled)[0]\n    probability = model.predict_proba(features_scaled)[0].max()\n    return jsonify({\n        'prediction': int(prediction),\n        'probability': float(probability),\n        'label': 'Default' if prediction == 1 else 'No Default'\n    })\n\nif __name__ == '__main__':\n    app.run(debug=False, host='0.0.0.0', port=5000)\n```\n\n## Model Monitoring\n\nModels degrade over time as data distribution changes (data drift):\n\n```python\nfrom evidently.report import Report\nfrom evidently.metric_preset import DataDriftPreset, ClassificationPreset\n\n# Generate drift report\nreport = Report(metrics=[DataDriftPreset(), ClassificationPreset()])\nreport.run(reference_data=X_train_df, current_data=X_production_df,\n           column_mapping=column_mapping)\nreport.save_html('drift_report.html')\n```\n\n## MLflow  Experiment Tracking\n\n```python\nimport mlflow\nimport mlflow.sklearn\n\nwith mlflow.start_run():\n    model = RandomForestClassifier(n_estimators=100, max_depth=6)\n    model.fit(X_train, y_train)\n\n    accuracy = accuracy_score(y_test, model.predict(X_test))\n    auc = roc_auc_score(y_test, model.predict_proba(X_test)[:,1])\n\n    mlflow.log_param('n_estimators', 100)\n    mlflow.log_param('max_depth', 6)\n    mlflow.log_metric('accuracy', accuracy)\n    mlflow.log_metric('roc_auc', auc)\n    mlflow.sklearn.log_model(model, 'model')\n```\n\n## Practical Task\n\nDeploy your best model from this course as a REST API using Flask. Containerise it with Docker. Set up basic monitoring: log every prediction with timestamp, input features, and output. Create a simple dashboard showing prediction volume and average confidence over time.\n\n## Self-Check\n1. What is data drift and why does it matter for deployed models?\n2. What is MLflow used for?\n3. What is the difference between model deployment and MLOps?",
7,$ts);

ins_lesson($pdo,$lid,19,"Capstone: ML System in Production",
"## Final Project Brief\n\nYou will build, evaluate, and deploy a complete machine learning system that solves a real business problem.\n\n## Project Scenario\n\nYou are the lead ML engineer at a Nigerian telecommunications company. The business wants to predict which customers are likely to churn (cancel their subscription) in the next 30 days, so the retention team can intervene proactively.\n\n## Dataset Features\n\nCreate or download a telecom churn dataset with:\n- customer_id, tenure_months, monthly_charge, total_charges\n- contract_type (month-to-month, 1-year, 2-year)\n- internet_service, phone_service, streaming_tv\n- payment_method, paperless_billing\n- num_support_calls, num_complaints\n- churn (target: 0=stayed, 1=churned)\n\n## Phase 1: Exploratory Analysis\n- Churn rate overall and by segment\n- Feature distributions for churned vs retained customers\n- Correlation analysis\n- Identify top 5 churn risk factors\n\n## Phase 2: Feature Engineering\n- Create charge_per_month_tenure ratio\n- Encode contract type (ordinal: month-to-month=0, 1-year=1, 2-year=2)\n- Create high_support_user flag (calls > 3)\n- Scale numeric features\n\n## Phase 3: Modelling\n- Baseline: Logistic Regression\n- Advanced: XGBoost with Optuna tuning\n- Handle class imbalance with SMOTE\n- Evaluate: ROC-AUC, Precision-Recall curve, F1\n- Interpret: SHAP values for top 10 features\n\n## Phase 4: Business Impact Analysis\n- Calculate expected revenue saved if top 20% at-risk customers are retained\n- Determine optimal probability threshold (balance precision vs recall)\n- Create customer risk segments: High/Medium/Low\n\n## Phase 5: Deployment\n- Flask API: POST /predict with customer features, returns churn probability and risk segment\n- Streamlit dashboard: Upload CSV of customers, get churn predictions, download results\n- MLflow: Track all experiments\n- Docker: Containerise the application\n\n## Deliverables\n1. GitHub repository (clean code, README, requirements.txt)\n2. Jupyter Notebook with complete analysis\n3. Deployed Flask API (local or cloud)\n4. Streamlit dashboard\n5. MLflow experiment tracking screenshots\n6. Business presentation (10 slides)\n7. Model card (1 page: purpose, performance, limitations, fairness)\n\n## Evaluation Criteria\n- EDA quality and business insight (15%)\n- Feature engineering (15%)\n- Model performance (ROC-AUC > 0.80) (25%)\n- Code quality and MLOps practices (20%)\n- Business impact analysis (15%)\n- Presentation and documentation (10%)\n\n## Self-Check\n1. What ROC-AUC score did you achieve and is it good enough for production?\n2. How would you explain the model's decision to a customer who was flagged as high churn risk?\n3. What would you monitor in production to detect model degradation?",
8,$ts);

echo "ML lessons: done\n";
