<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/config/db.php';
$pdo->exec("SET FOREIGN_KEY_CHECKS=0");
$ts = '2026-04-15 08:00:00';

/* ── Courses ── */
$pdo->prepare("INSERT IGNORE INTO lms_courses (id,title,slug,description,short_description,price,level,is_active,created_at) VALUES (?,?,?,?,?,?,?,1,?)")
    ->execute([17,'Data Science','data-science','Master data science from data wrangling to machine learning, statistical analysis, and real-world project deployment.','From raw data to actionable insights.',380000.00,'advanced',$ts]);
$pdo->prepare("INSERT IGNORE INTO lms_courses (id,title,slug,description,short_description,price,level,is_active,created_at) VALUES (?,?,?,?,?,?,?,1,?)")
    ->execute([18,'Artificial Intelligence (AI)','artificial-intelligence','Comprehensive AI course covering neural networks, deep learning, NLP, computer vision, and AI ethics with hands-on projects.','Build intelligent systems with AI.',420000.00,'advanced',$ts]);
$pdo->prepare("INSERT IGNORE INTO lms_courses (id,title,slug,description,short_description,price,level,is_active,created_at) VALUES (?,?,?,?,?,?,?,1,?)")
    ->execute([19,'Machine Learning (ML)','machine-learning','Learn supervised, unsupervised, and reinforcement learning algorithms, model evaluation, feature engineering, and ML deployment.','Algorithms that learn from data.',400000.00,'advanced',$ts]);
echo "Courses inserted\n";

/* ── Exams ── */
$pdo->prepare("INSERT IGNORE INTO lms_exams (id,course_id,title,duration_minutes,total_questions,pass_mark,total_marks,is_published,created_at) VALUES (?,?,?,?,?,?,?,1,?)")
    ->execute([61,17,'Data Science — Final Exam',40,10,50,10,$ts]);
$pdo->prepare("INSERT IGNORE INTO lms_exams (id,course_id,title,duration_minutes,total_questions,pass_mark,total_marks,is_published,created_at) VALUES (?,?,?,?,?,?,?,1,?)")
    ->execute([62,18,'Artificial Intelligence — Final Exam',40,10,50,10,$ts]);
$pdo->prepare("INSERT IGNORE INTO lms_exams (id,course_id,title,duration_minutes,total_questions,pass_mark,total_marks,is_published,created_at) VALUES (?,?,?,?,?,?,?,1,?)")
    ->execute([63,19,'Machine Learning — Final Exam',40,10,50,10,$ts]);
echo "Exams inserted\n";

/* ── Lessons helper ── */
$lid = (int)$pdo->query("SELECT COALESCE(MAX(id),0)+1 FROM lms_lessons")->fetchColumn();
$lStmt = $pdo->prepare("INSERT IGNORE INTO lms_lessons (id,course_id,title,content,sort_order,is_published,created_at) VALUES (?,?,?,?,?,1,?)");

function L(PDOStatement $s, int &$lid, int $cid, string $title, string $content, int $sort, string $ts): void {
    $s->execute([$lid++, $cid, $title, $content, $sort, $ts]);
}

/* ═══════════════════════════════════════════════════════
   DATA SCIENCE — course_id=17
═══════════════════════════════════════════════════════ */
L($lStmt,$lid,17,"Introduction to Data Science",
"## What is Data Science?\n\nData science is an interdisciplinary field that uses scientific methods, processes, algorithms, and systems to extract knowledge and insights from structured and unstructured data.\n\n## The Data Science Lifecycle\n\n1. Problem Definition: What business question are we answering?\n2. Data Collection: Gather data from databases, APIs, web scraping, surveys\n3. Data Cleaning: Handle missing values, outliers, duplicates, inconsistencies\n4. Exploratory Data Analysis (EDA): Understand distributions, correlations, patterns\n5. Feature Engineering: Create and select the most predictive variables\n6. Modelling: Apply statistical or machine learning models\n7. Evaluation: Measure model performance with appropriate metrics\n8. Deployment: Serve the model in production\n9. Monitoring: Track model performance over time\n\n## Data Science vs Related Fields\n\n- Data Analysis: Focuses on describing and interpreting existing data\n- Data Engineering: Builds pipelines and infrastructure for data\n- Machine Learning: Algorithms that learn patterns from data\n- Data Science: Combines all three with domain expertise\n\n## Essential Tools\n\n- Python: Primary language (pandas, numpy, scikit-learn, matplotlib)\n- R: Statistical computing and visualisation\n- SQL: Query and manipulate relational databases\n- Jupyter Notebook: Interactive development environment\n- Git: Version control for code and experiments\n\n## Practical Task\n\nInstall Anaconda (anaconda.com). Create a new Jupyter Notebook. Import pandas and numpy. Load a CSV file from Kaggle. Display the first 10 rows, check data types, and count missing values.\n\n## Self-Check\n1. What are the 9 stages of the data science lifecycle?\n2. What is the difference between data science and data analysis?\n3. What Python libraries are essential for data science?",
1,$ts);

L($lStmt,$lid,17,"Python for Data Science",
"## NumPy and pandas Fundamentals\n\n```python\nimport numpy as np\nimport pandas as pd\n\n# NumPy arrays\narr = np.array([1, 2, 3, 4, 5])\nprint(arr.mean(), arr.std())  # 3.0, 1.41\n\n# pandas DataFrame\ndf = pd.read_csv('students.csv')\nprint(df.shape)           # (rows, cols)\nprint(df.describe())      # Statistical summary\nprint(df.isnull().sum())  # Missing values\n\n# Filter and aggregate\ndf[df['score'] > 70].groupby('course')['score'].agg(['mean','count'])\n\n# Clean\ndf.dropna(subset=['score'])\ndf['score'].fillna(df['score'].mean())\ndf.drop_duplicates(subset=['email'])\n```\n\n## Visualisation\n\n```python\nimport matplotlib.pyplot as plt\nimport seaborn as sns\n\nsns.histplot(df['score'], bins=20, kde=True)\nsns.heatmap(df.corr(), annot=True, cmap='coolwarm')\nsns.scatterplot(data=df, x='study_hours', y='score', hue='grade')\n```\n\n## Practical Task\n\nDownload a Nigerian Students Performance dataset from Kaggle. Load it into pandas. Perform: (1) data cleaning, (2) descriptive statistics, (3) correlation analysis, (4) 3 visualisations. Write a 1-paragraph insight summary.\n\n## Self-Check\n1. What is the difference between a NumPy array and a pandas DataFrame?\n2. How do you handle missing values in pandas?\n3. What chart type shows correlation between two variables?",
2,$ts);

L($lStmt,$lid,17,"Statistical Analysis & Probability",
"## Descriptive Statistics\n\nMeasures of Central Tendency: Mean (sensitive to outliers), Median (robust), Mode (most frequent)\nMeasures of Spread: Variance, Standard Deviation, IQR, Range\nShape: Skewness (asymmetry), Kurtosis (tail heaviness)\n\n## Probability Fundamentals\n\n- P(A): Probability of event A (0 to 1)\n- P(A|B): Conditional probability\n- Bayes Theorem: P(A|B) = P(B|A) * P(A) / P(B)\n\n## Key Distributions\n\n- Normal: Bell curve. 68-95-99.7 rule.\n- Binomial: Number of successes in n trials\n- Poisson: Number of events in a fixed interval\n\n## Hypothesis Testing\n\n```python\nfrom scipy import stats\n\n# t-test: compare two group means\nt_stat, p_value = stats.ttest_ind(group_a, group_b)\nprint(f't={t_stat:.3f}, p={p_value:.4f}')\n# If p < 0.05: reject null hypothesis\n\n# Correlation\nr, p = stats.pearsonr(df['study_hours'], df['score'])\nprint(f'r={r:.3f}, p={p:.4f}')\n```\n\nCommon tests: t-test (compare means), Chi-square (categorical independence), ANOVA (3+ groups), Pearson/Spearman correlation\n\n## Practical Task\n\nUsing exam score data: (1) Calculate all descriptive statistics. (2) Test whether students who studied 5+ hours scored significantly higher (t-test). (3) Check if gender and pass/fail are independent (chi-square). Report findings with interpretation.\n\n## Self-Check\n1. When should you use median instead of mean?\n2. What does a p-value of 0.03 mean?\n3. What is the difference between correlation and causation?",
3,$ts);

L($lStmt,$lid,17,"Data Wrangling & Feature Engineering",
"## Data Wrangling\n\nData scientists spend 60-80% of their time cleaning and preparing data. Common issues: missing values, duplicates, wrong types, inconsistent categories, outliers.\n\n## Handling Missing Values\n\n```python\n# Check\ndf.isnull().mean() * 100  # Percentage missing per column\n\n# Drop\ndf.dropna(subset=['critical_col'])\n\n# Impute\ndf['age'].fillna(df['age'].median(), inplace=True)\ndf['city'].fillna('Unknown', inplace=True)\n\n# KNN imputation\nfrom sklearn.impute import KNNImputer\nimputer = KNNImputer(n_neighbors=5)\ndf_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)\n```\n\n## Feature Engineering\n\n```python\n# Date features\ndf['year'] = df['date'].dt.year\ndf['month'] = df['date'].dt.month\ndf['is_weekend'] = df['date'].dt.dayofweek.isin([5,6]).astype(int)\n\n# Binning\ndf['age_group'] = pd.cut(df['age'], bins=[0,18,35,60,100],\n                         labels=['Youth','Adult','Middle','Senior'])\n\n# Encoding\ndf = pd.get_dummies(df, columns=['city'], drop_first=True)  # One-hot\ndf['gender_enc'] = df['gender'].map({'Male':1,'Female':0})   # Label\n\n# Scaling\nfrom sklearn.preprocessing import StandardScaler\nscaler = StandardScaler()\ndf[['age','income']] = scaler.fit_transform(df[['age','income']])\n\n# Interaction\ndf['income_per_age'] = df['income'] / (df['age'] + 1)\n```\n\n## Practical Task\n\nTake a messy dataset with intentional issues. Perform a complete wrangling pipeline: audit, clean, engineer 3 new features, encode categoricals, scale numerics. Document every decision.\n\n## Self-Check\n1. What is the difference between dropping and imputing missing values?\n2. Why do we scale features before modelling?\n3. What is one-hot encoding and when do you use it?",
4,$ts);

L($lStmt,$lid,17,"Machine Learning for Data Scientists",
"## Key ML Algorithms for Data Scientists\n\nRegression: Linear, Ridge, Lasso, Random Forest, XGBoost\nClassification: Logistic Regression, Decision Tree, Random Forest, XGBoost, SVM\n\n```python\nfrom sklearn.ensemble import RandomForestClassifier\nfrom sklearn.model_selection import train_test_split, cross_val_score\nfrom sklearn.metrics import classification_report, roc_auc_score\n\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)\n\nmodel = RandomForestClassifier(n_estimators=100, random_state=42)\nmodel.fit(X_train, y_train)\n\ny_pred = model.predict(X_test)\ny_prob = model.predict_proba(X_test)[:,1]\n\nprint(classification_report(y_test, y_pred))\nprint(f'ROC-AUC: {roc_auc_score(y_test, y_prob):.4f}')\n\n# Cross-validation\nscores = cross_val_score(model, X, y, cv=5, scoring='f1_macro')\nprint(f'CV F1: {scores.mean():.3f} +/- {scores.std():.3f}')\n```\n\n## Model Evaluation Metrics\n\nClassification: Accuracy, Precision, Recall, F1, ROC-AUC\nRegression: MAE, RMSE, R2, MAPE\n\nKey insight: Accuracy is misleading for imbalanced datasets. Use F1 or ROC-AUC.\n\n## Practical Task\n\nBuild a student pass/fail prediction model. Features: study hours, attendance, previous scores, assignment completion. Use Random Forest. Evaluate with classification report and ROC-AUC. Identify the top 3 most important features.\n\n## Self-Check\n1. What is the difference between precision and recall?\n2. Why is accuracy a poor metric for imbalanced datasets?\n3. What is cross-validation and why is it important?",
5,$ts);

L($lStmt,$lid,17,"Data Visualisation & Storytelling",
"## Choosing the Right Chart\n\n| Goal | Chart Type |\n|---|---|\n| Compare categories | Bar chart |\n| Show trend over time | Line chart |\n| Show distribution | Histogram, Box plot |\n| Show correlation | Scatter plot |\n| Show proportions | Pie chart (max 5 slices) |\n\n## Advanced Visualisation with Plotly\n\n```python\nimport plotly.express as px\n\n# Interactive scatter\nfig = px.scatter(df, x='study_hours', y='score', color='grade',\n                 size='attendance', hover_data=['name'],\n                 title='Study Hours vs Score')\nfig.show()\n```\n\n## Streamlit Dashboard\n\n```python\nimport streamlit as st\nimport plotly.express as px\n\nst.title('Student Performance Dashboard')\ncourse = st.selectbox('Select Course', df['course'].unique())\nfiltered = df[df['course'] == course]\n\ncol1, col2 = st.columns(2)\ncol1.metric('Average Score', f\"{filtered['score'].mean():.1f}\")\ncol2.metric('Pass Rate', f\"{(filtered['score']>=50).mean()*100:.1f}%\")\n\nfig = px.histogram(filtered, x='score', title='Score Distribution')\nst.plotly_chart(fig)\n```\n\n## Data Storytelling\n\nStructure: Context (situation) -> Conflict (problem/opportunity) -> Resolution (what data shows we should do)\n\n## Practical Task\n\nBuild a Streamlit dashboard for a student performance dataset. Include: 3 KPI metrics, score distribution chart, trend over time, top 10 students table, and a course filter.\n\n## Self-Check\n1. What chart type is best for showing a trend over time?\n2. What is data storytelling and why does it matter?\n3. What is the difference between Plotly and Matplotlib?",
6,$ts);

L($lStmt,$lid,17,"Big Data & Cloud Data Science",
"## What is Big Data?\n\nBig Data: datasets too large for traditional tools. Characterised by 5 Vs: Volume, Velocity, Variety, Veracity, Value.\n\n## Big Data Technologies\n\nStorage: Hadoop HDFS, Amazon S3, Google Cloud Storage\nProcessing: Apache Spark (100x faster than MapReduce), Apache Kafka (streaming)\nDatabases: MongoDB (document), Cassandra (wide-column), BigQuery (data warehouse)\n\n## PySpark Basics\n\n```python\nfrom pyspark.sql import SparkSession\n\nspark = SparkSession.builder.appName('DataScience').getOrCreate()\ndf = spark.read.csv('large_dataset.csv', header=True, inferSchema=True)\n\n# Lazy evaluation\ndf.filter(df['score'] > 70).groupBy('course').agg({'score': 'mean'}).show()\n\n# Convert small results to pandas\npandas_df = df.toPandas()\n```\n\n## Cloud Platforms\n\n- AWS SageMaker: Build, train, deploy ML models at scale\n- Google Vertex AI: Unified ML platform on GCP\n- Azure Machine Learning: Microsoft ML platform\n- Databricks: Spark-based unified analytics\n- Google Colab: Free GPU/TPU notebooks\n\n## Practical Task\n\nCreate a Google Colab notebook. Load a large dataset (1M+ rows). Perform aggregations and visualisations. Compare pandas vs PySpark performance for the same operations.\n\n## Self-Check\n1. What are the 5 Vs of Big Data?\n2. What is the main advantage of Apache Spark over Hadoop MapReduce?\n3. Name 3 cloud data science platforms.",
7,$ts);

L($lStmt,$lid,17,"Capstone: End-to-End Data Science Project",
"## Final Project: Loan Default Prediction\n\nYou are a data scientist at a Nigerian fintech company. Build a model to predict loan defaults and a dashboard for the risk team.\n\n## Dataset Features\n\napplicant_age, income, employment_years, loan_amount, loan_purpose, credit_score, existing_loans, education_level, state, gender, default (target)\n\n## Phase 1: EDA\n- Descriptive statistics for all features\n- Missing value analysis and treatment\n- Distribution plots and correlation analysis\n- Class imbalance check\n\n## Phase 2: Feature Engineering\n- Create debt-to-income ratio\n- Encode categorical variables\n- Scale numeric features\n- Handle class imbalance (SMOTE or class weights)\n- Feature selection (top 10 by importance)\n\n## Phase 3: Modelling\n- Train 3 models: Logistic Regression, Random Forest, XGBoost\n- Cross-validate each (5-fold)\n- Tune hyperparameters\n- Select best model by ROC-AUC and F1\n\n## Phase 4: Evaluation\n- Confusion matrix, ROC curve, AUC\n- Feature importance plot\n- SHAP values for explainability\n\n## Phase 5: Deployment\n- Save model with joblib\n- Build Streamlit app: input applicant details, get default probability\n- Deploy to Streamlit Cloud (free)\n\n## Deliverables\n- Jupyter Notebook, Streamlit dashboard, 10-slide presentation, 1-page executive summary\n\n## Self-Check\n1. What metric would you prioritise for a fraud detection model and why?\n2. How would you explain your model to a non-technical bank manager?\n3. What steps if your model performs well in testing but poorly in production?",
8,$ts);

echo "Data Science: 8 lessons\n";
