<?php
require_once __DIR__ . '/../config/db.php';

$ts = '2026-02-16 07:11:08';
$lessons = [
  [2, 'Advanced Typography & Type Systems', 'Advanced typography creates consistent, scalable type hierarchies across all brand touchpoints.\n\n## Type Scale\nA type scale defines the sizes used in a design system. Use tools like typescale.com to generate scales based on ratios like Major Third (1.25x) or Perfect Fourth (1.333x).\n\n## Variable Fonts\nVariable fonts contain multiple styles in a single file, reducing file size and enabling smooth weight animations. Examples: Inter, Roboto Flex.\n\n## Kerning & Tracking\n- Tracking: Uniform spacing between all characters\n- Kerning: Adjusting space between specific pairs (AV, WA)\n- Leading: Vertical space between lines\n\n## Advanced Layout\n- Drop caps: Large initial letter at paragraph start\n- Pull quotes: Highlighted quotes from body text\n- Hanging punctuation: Quotation marks outside the text margin\n- Baseline grid: All text aligns to consistent vertical rhythm\n\n## Practical Task\nCreate a 4-page editorial layout in InDesign. Establish a type scale, apply a baseline grid, and use at least 3 levels of typographic hierarchy. Include a pull quote and drop cap.\n\n## Self-Check\n1. What is the difference between tracking and kerning?\n2. What is a variable font and what are its advantages?\n3. How does a type scale improve design consistency?', 1],
  [2, 'Advanced Colour & Brand Systems', 'A colour system defines how colour is used consistently across all brand touchpoints.\n\n## Colour Tokens\nColour tokens are named variables:\n- Primary: Main brand colour (buttons, links)\n- Secondary: Supporting colour (accents)\n- Neutral: Greys for text, backgrounds, borders\n- Semantic: success=green, error=red, warning=amber, info=blue\n\n## Colour Accessibility\nWCAG AA standard: 4.5:1 for normal text, 3:1 for large text.\nTools: WebAIM Contrast Checker, Figma Contrast plugin.\n\n## Dark Mode\nDark mode is not simply inverting colours:\n- Use dark grey (not pure black): #121212 or #1E1E1E\n- Reduce saturation in dark mode\n- Maintain the same contrast ratios\n- Test all semantic colours in both modes\n\n## Data Visualisation Colour\n- Sequential palettes: ordered data (light to dark)\n- Diverging palettes: data with a meaningful midpoint\n- Categorical palettes: unordered groups\n- Always provide non-colour indicators for accessibility\n\n## Practical Task\nCreate a complete colour system for a fictional SaaS product. Define primary, secondary, neutral, and semantic tokens. Test all combinations for WCAG AA compliance.\n\n## Self-Check\n1. What is the WCAG AA contrast ratio for normal text?\n2. What are colour tokens and why are they useful?\n3. Why is dark mode not simply an inversion of light mode?', 2],
  [2, 'Advanced Layout & Grid Systems', 'A modular grid divides the page into both columns and rows, creating a matrix of modules for maximum layout flexibility.\n\n## The 12-Column Grid\nThe 12-column grid is the most widely used because 12 is divisible by 2, 3, 4, and 6. Bootstrap, Material Design, and most CSS frameworks use it.\n\n## Gestalt Principles\n- Figure/Ground: Distinguishing object from background\n- Similarity: Similar elements are perceived as a group\n- Continuation: The eye follows lines and curves\n- Closure: The mind completes incomplete shapes\n- Common Fate: Elements moving together are grouped\n\n## Editorial Layout Techniques\n- Z-pattern: Eye moves in a Z shape (text-heavy pages)\n- F-pattern: Eye scans horizontally then vertically (web content)\n- Golden ratio: 1:1.618 proportion creates pleasing layouts\n- Rule of thirds: Place key elements at grid intersections\n\n## Responsive Layout\n- Mobile: 320-767px  single column\n- Tablet: 768-1023px  2-column layouts\n- Desktop: 1024px+  full multi-column layouts\n\n## Practical Task\nDesign a magazine cover and 2-page spread using a modular grid. Apply the rule of thirds for the cover image. Use the F-pattern for the article layout.\n\n## Self-Check\n1. Why is the 12-column grid so widely used?\n2. Name 3 Gestalt principles and explain how they affect layout.\n3. What is the difference between Z-pattern and F-pattern layouts?', 3],
  [2, 'Motion Graphics & Animation', 'Motion design adds the dimension of time to graphic design, used in title sequences, explainer videos, social media animations, and UI transitions.\n\n## 12 Principles of Animation (Disney)\n1. Squash and Stretch: Gives weight and flexibility\n2. Anticipation: Small movement before the main action\n3. Staging: Presenting an idea clearly\n4. Slow In and Slow Out (Easing): Gradual acceleration/deceleration\n5. Arc: Natural movements follow curved paths\n6. Secondary Action: Supporting actions that add richness\n7. Timing: Number of frames determines speed\n8. Exaggeration: Amplifying actions for effect\n9. Appeal: Designs that are engaging and charismatic\n\n## Adobe After Effects Basics\n- Composition: The canvas where animation happens\n- Timeline: Where keyframes are placed\n- Keyframes: Points in time defining a property value\n- Easing: Controlling acceleration (Easy Ease = natural movement)\n\n## Easing Functions\n- Linear: Constant speed  feels mechanical\n- Ease In: Starts slow, ends fast\n- Ease Out: Starts fast, ends slow (most natural for UI)\n- Ease In-Out: Slow start and end  best for most animations\n\n## Practical Task\nCreate a 10-second animated logo reveal in After Effects. Apply at least 3 animation principles. Export as MP4 and GIF.\n\n## Self-Check\n1. What is easing and why does it make animations feel natural?\n2. Name 5 of the 12 principles of animation.\n3. What is the difference between Ease In and Ease Out?', 4],
  [2, 'Advanced Branding & Strategy', 'Brand strategy is the long-term plan for developing a brand to achieve specific goals. Strategy comes first; identity follows.\n\n## Brand Architecture\n- Monolithic (Branded House): One master brand for everything (Apple, Google)\n- Endorsed: Sub-brands endorsed by the parent (Marriott Courtyard)\n- Pluralistic (House of Brands): Independent brands under one company (P&G)\n\n## Brand Positioning\nPositioning defines where your brand sits in the market:\n\nFor [target audience], [brand name] is the [category] that [key benefit] because [reason to believe].\n\nExample: For young professionals, Slack is the team communication tool that reduces email overload because it organises conversations by channel.\n\n## Rebranding\nWhen to rebrand:\n- Mergers and acquisitions\n- Significant shift in target audience\n- Outdated visual identity\n- Reputation management\n- Expansion into new markets\n\nRebranding risks: alienating existing customers, losing brand equity. Always research before rebranding.\n\n## Practical Task\nConduct a brand audit for a real or fictional company. Analyse their current brand identity, positioning, and consistency across touchpoints. Write a 1-page brand strategy recommendation.\n\n## Self-Check\n1. What is the difference between brand strategy and brand identity?\n2. What are the three types of brand architecture?\n3. Write a positioning statement for a fictional brand.', 5],
  [2, 'Freelancing & Design Business', 'Freelancing gives you creative freedom and flexibility, but requires business skills alongside design skills.\n\n## Setting Up Your Business\n1. Register your business (sole trader or limited company)\n2. Open a business bank account\n3. Get professional indemnity insurance\n4. Set up accounting (Wave, FreshBooks, or QuickBooks)\n5. Create contracts  never work without a signed contract\n\n## Finding Clients\n- Warm outreach: Friends, family, former colleagues\n- Cold outreach: Research target companies, send personalised emails\n- Social media: LinkedIn, Instagram  share your work consistently\n- Freelance platforms: Upwork, Fiverr, 99designs\n- Referrals: Your best clients come from happy existing clients\n\n## Pricing Models\n- Project-based: Defined scope, most common\n- Hourly: Undefined scope, ongoing work\n- Retainer: Ongoing relationship, predictable income\n- Value-based: High-impact projects, experienced designers\n\n## The Client Contract Must Include\n- Scope of work (exactly what is included)\n- Timeline and milestones\n- Payment terms (deposit, instalments, final payment)\n- Number of revision rounds\n- Kill fee clause\n- Intellectual property ownership\n\n## Practical Task\nWrite a project proposal and contract for a fictional logo design project. Include all contract elements. Set a project price using the project-based model.\n\n## Self-Check\n1. What is professional indemnity insurance?\n2. What must a client contract include?\n3. What is the difference between project-based and value-based pricing?', 6],
  [2, 'Packaging & Environmental Design', 'Packaging design is where graphic design meets the physical world. It must be functional, protective, and visually compelling.\n\n## Packaging Design Considerations\n- Structural: Shape, material, opening mechanism, stackability\n- Visual: Brand identity, typography, colour, imagery\n- Regulatory: Ingredients, nutritional info, barcodes, legal text\n- Sustainability: Recyclable materials, minimal waste, eco-friendly inks\n\n## Dieline\nA dieline is the flat, unfolded template of a package. Designers work on the dieline, which is then folded into the 3D package.\n\n## Label Design\n- Front panel: Brand name, product name, key visual\n- Back panel: Ingredients, instructions, legal text, barcode\n- Neck label (bottles): Brand mark or tagline\n\n## Environmental & Wayfinding Design\n- Wayfinding: Signs, maps, and directional systems (airports, hospitals)\n- Retail design: In-store graphics, window displays, point-of-sale\n- Exhibition design: Trade show booths, museum displays\n- Murals & supergraphics: Large-scale wall art\n\n## Practical Task\nDesign packaging for a fictional artisan coffee brand. Create the dieline for a 250g coffee bag. Design all panels: front, back, side gussets. Include brand identity, product information, and a sustainability message.\n\n## Self-Check\n1. What is a dieline and how is it used in packaging design?\n2. What information is legally required on food packaging?\n3. What is wayfinding design? Give two real-world examples.', 7],
  [2, 'Capstone: Advanced Brand Campaign', 'You will create a comprehensive brand campaign for a fictional company undergoing a rebrand.\n\n## Scenario\nApex Digital, a 10-year-old Nigerian tech company, is rebranding to appeal to a younger, pan-African audience. They offer software solutions for SMEs.\n\n## Deliverables\n\n### 1. Brand Audit\n- Analysis of the existing brand\n- Competitor landscape (3 competitors)\n- Target audience personas (2 personas)\n- Positioning statement\n\n### 2. New Visual Identity\n- Logo suite (primary, secondary, icon)\n- Colour system (tokens with HEX, RGB, CMYK)\n- Typography system\n- Photography/illustration direction\n\n### 3. Campaign Materials\n- Billboard design (3000 x 1000px)\n- Social media campaign (5 posts)\n- Email newsletter header\n- App icon and splash screen\n- Branded merchandise mockup\n\n### 4. Brand Guidelines (PDF, minimum 20 pages)\n- Full brand story and values\n- Logo usage rules\n- Colour and typography specifications\n- Tone of voice with examples\n- Incorrect usage examples\n\n## Evaluation Criteria\n- Strategic thinking and rationale (20%)\n- Visual identity strength (25%)\n- Campaign consistency and creativity (25%)\n- Production quality (20%)\n- Brand guidelines completeness (10%)\n\n## Self-Check\n1. Does every deliverable feel like it belongs to the same brand?\n2. Is your brand strategy clearly reflected in the visual choices?\n3. Could another designer maintain this brand using your guidelines?', 8],
];

$pdo->exec('SET FOREIGN_KEY_CHECKS=0');
// Delete existing course 2 lessons
$pdo->exec('DELETE FROM lms_lessons WHERE course_id=2');

$stmt = $pdo->prepare('INSERT INTO lms_lessons (course_id, title, content, sort_order, is_published, created_at) VALUES (?,?,?,?,1,?)');
$count = 0;
foreach($lessons as $l) {
    $stmt->execute([$l[0], $l[1], $l[2], $l[3], $ts]);
    $count++;
}
$pdo->exec('SET FOREIGN_KEY_CHECKS=1');
echo 'Inserted ' . $count . ' lessons for course 2' . PHP_EOL;
echo 'Total lessons: ' . $pdo->query('SELECT COUNT(*) FROM lms_lessons')->fetchColumn() . PHP_EOL;
echo 'Course 2 lessons: ' . $pdo->query('SELECT COUNT(*) FROM lms_lessons WHERE course_id=2')->fetchColumn() . PHP_EOL;

